//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.03.28 at 03:37:43 PM CEST 
//


package org.matsim.contrib.grips.io.jaxb.gripsconfig;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for grips_config_type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="grips_config_type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="networkFile" type="{}fileType"/>
 *         &lt;element name="evacuationAreaFile" type="{}fileType"/>
 *         &lt;element name="populationFile" type="{}fileType"/>
 *         &lt;element name="outputDir" type="{}fileType"/>
 *         &lt;element name="sampleSize" type="{}sampleSizeType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "grips_config_type", propOrder = {
    "networkFile",
    "evacuationAreaFile",
    "populationFile",
    "outputDir",
    "sampleSize"
})
public class GripsConfigType {

    @XmlElement(required = true)
    protected FileType networkFile;
    @XmlElement(required = true)
    protected FileType evacuationAreaFile;
    @XmlElement(required = true)
    protected FileType populationFile;
    @XmlElement(required = true)
    protected FileType outputDir;
    protected double sampleSize;

    /**
     * Gets the value of the networkFile property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getNetworkFile() {
        return networkFile;
    }

    /**
     * Sets the value of the networkFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setNetworkFile(FileType value) {
        this.networkFile = value;
    }

    /**
     * Gets the value of the evacuationAreaFile property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getEvacuationAreaFile() {
        return evacuationAreaFile;
    }

    /**
     * Sets the value of the evacuationAreaFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setEvacuationAreaFile(FileType value) {
        this.evacuationAreaFile = value;
    }

    /**
     * Gets the value of the populationFile property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getPopulationFile() {
        return populationFile;
    }

    /**
     * Sets the value of the populationFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setPopulationFile(FileType value) {
        this.populationFile = value;
    }

    /**
     * Gets the value of the outputDir property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getOutputDir() {
        return outputDir;
    }

    /**
     * Sets the value of the outputDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setOutputDir(FileType value) {
        this.outputDir = value;
    }

    /**
     * Gets the value of the sampleSize property.
     * 
     */
    public double getSampleSize() {
        return sampleSize;
    }

    /**
     * Sets the value of the sampleSize property.
     * 
     */
    public void setSampleSize(double value) {
        this.sampleSize = value;
    }

}
