language: java
jdk: oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer  # https://github.com/travis-ci/travis-ci/issues/3259
script:
  - mvn package -B -Dmatsim.preferLocalDtds=true -Dmaven.test.redirectTestOutputToFile
# --fail-at-end
env:
  global:
    - MAVEN_OPTS="-Xmx2g"
cache:
  directories:
  - $HOME/.m2

