//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.08.04 at 02:05:46 PM CEST
//


package playground.gregor.grips.jaxb.inspire.basetypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import net.opengis.gml.v_3_2_1.AbstractFeatureType;
import net.opengis.gml.v_3_2_1.AbstractMetadataPropertyType;
import net.opengis.gml.v_3_2_1.FeaturePropertyType;
import org.isotc211.iso19139.d_2007_04_17.gmd.MDMetadataType;


/**
 * <p>Java class for SpatialDataSetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpatialDataSetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="identifier" type="{urn:x-inspire:specification:gmlas:BaseTypes:3.2}IdentifierPropertyType"/>
 *         &lt;element name="metadata">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractMetadataPropertyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element ref="{http://www.isotc211.org/2005/gmd}MD_Metadata"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{http://www.opengis.net/gml/3.2}AssociationAttributeGroup"/>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="member" type="{http://www.opengis.net/gml/3.2}FeaturePropertyType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpatialDataSetType", propOrder = {
		"rest"
})
public class SpatialDataSetType
extends AbstractFeatureType
{

	@XmlElementRefs({
		@XmlElementRef(name = "metadata", namespace = "urn:x-inspire:specification:gmlas:BaseTypes:3.2", type = JAXBElement.class),
		@XmlElementRef(name = "identifier", namespace = "urn:x-inspire:specification:gmlas:BaseTypes:3.2", type = JAXBElement.class),
		@XmlElementRef(name = "member", namespace = "urn:x-inspire:specification:gmlas:BaseTypes:3.2", type = JAXBElement.class)
	})
	protected List<JAXBElement<?>> rest;

	/**
	 * Gets the rest of the content model.
	 * 
	 * <p>
	 * You are getting this "catch-all" property because of the following reason:
	 * The field name "Identifier" is used by two different parts of a schema. See:
	 * line 59 of file:/Users/laemmel/Documents/workspace/playgrounds/gregor/xsd/INSPIRE/inspire-foss-read-only/schemas/inspire/v3.0.1/BaseTypes.xsd
	 * line 41 of http://schemas.opengis.net/gml/3.2.1/gmlBase.xsd
	 * <p>
	 * To get rid of this property, apply a property customization to one
	 * of both of the following declarations to change their names:
	 * Gets the value of the rest property.
	 * 
	 * <p>
	 * This accessor method returns a reference to the live list,
	 * not a snapshot. Therefore any modification you make to the
	 * returned list will be present inside the JAXB object.
	 * This is why there is not a <CODE>set</CODE> method for the rest property.
	 * 
	 * <p>
	 * For example, to add a new item, do as follows:
	 * <pre>
	 *    getRest().add(newItem);
	 * </pre>
	 * 
	 * 
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link JAXBElement }{@code <}{@link FeaturePropertyType }{@code >}
	 * {@link JAXBElement }{@code <}{@link IdentifierPropertyType }{@code >}
	 * {@link JAXBElement }{@code <}{@link SpatialDataSetType.Metadata }{@code >}
	 * 
	 * 
	 */
	public List<JAXBElement<?>> getRest() {
		if (this.rest == null) {
			this.rest = new ArrayList<JAXBElement<?>>();
		}
		return this.rest;
	}


	/**
	 * <p>Java class for anonymous complex type.
	 * 
	 * <p>The following schema fragment specifies the expected content contained within this class.
	 * 
	 * <pre>
	 * &lt;complexType>
	 *   &lt;complexContent>
	 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractMetadataPropertyType">
	 *       &lt;sequence minOccurs="0">
	 *         &lt;element ref="{http://www.isotc211.org/2005/gmd}MD_Metadata"/>
	 *       &lt;/sequence>
	 *       &lt;attGroup ref="{http://www.opengis.net/gml/3.2}AssociationAttributeGroup"/>
	 *     &lt;/extension>
	 *   &lt;/complexContent>
	 * &lt;/complexType>
	 * </pre>
	 * 
	 * 
	 */
	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = {
			"mdMetadata"
	})
	public static class Metadata
	extends AbstractMetadataPropertyType
	{

		@XmlElement(name = "MD_Metadata", namespace = "http://www.isotc211.org/2005/gmd")
		protected MDMetadataType mdMetadata;
		@XmlAttribute
		protected List<String> nilReason;
		@XmlAttribute(namespace = "http://www.opengis.net/gml/3.2")
		@XmlSchemaType(name = "anyURI")
		protected String remoteSchema;
		/**
		 * 
		 * 
		 */
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		public final static String TYPE = "simple";
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		@XmlSchemaType(name = "anyURI")
		protected String href;
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		@XmlSchemaType(name = "anyURI")
		protected String role;
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		@XmlSchemaType(name = "anyURI")
		protected String arcrole;
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		protected String title;
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		protected String show;
		@XmlAttribute(namespace = "http://www.w3.org/1999/xlink")
		protected String actuate;

		/**
		 * Gets the value of the mdMetadata property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link MDMetadataType }
		 * 
		 */
		public MDMetadataType getMDMetadata() {
			return this.mdMetadata;
		}

		/**
		 * Sets the value of the mdMetadata property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link MDMetadataType }
		 * 
		 */
		public void setMDMetadata(MDMetadataType value) {
			this.mdMetadata = value;
		}

		public boolean isSetMDMetadata() {
			return (this.mdMetadata!= null);
		}

		/**
		 * Gets the value of the nilReason property.
		 * 
		 * <p>
		 * This accessor method returns a reference to the live list,
		 * not a snapshot. Therefore any modification you make to the
		 * returned list will be present inside the JAXB object.
		 * This is why there is not a <CODE>set</CODE> method for the nilReason property.
		 * 
		 * <p>
		 * For example, to add a new item, do as follows:
		 * <pre>
		 *    getNilReason().add(newItem);
		 * </pre>
		 * 
		 * 
		 * <p>
		 * Objects of the following type(s) are allowed in the list
		 * {@link String }
		 * 
		 * 
		 */
		public List<String> getNilReason() {
			if (this.nilReason == null) {
				this.nilReason = new ArrayList<String>();
			}
			return this.nilReason;
		}

		public boolean isSetNilReason() {
			return ((this.nilReason!= null)&&(!this.nilReason.isEmpty()));
		}

		public void unsetNilReason() {
			this.nilReason = null;
		}

		/**
		 * Gets the value of the remoteSchema property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getRemoteSchema() {
			return this.remoteSchema;
		}

		/**
		 * Sets the value of the remoteSchema property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setRemoteSchema(String value) {
			this.remoteSchema = value;
		}

		public boolean isSetRemoteSchema() {
			return (this.remoteSchema!= null);
		}

		/**
		 * Gets the value of the href property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getHref() {
			return this.href;
		}

		/**
		 * Sets the value of the href property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setHref(String value) {
			this.href = value;
		}

		public boolean isSetHref() {
			return (this.href!= null);
		}

		/**
		 * Gets the value of the role property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getRole() {
			return this.role;
		}

		/**
		 * Sets the value of the role property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setRole(String value) {
			this.role = value;
		}

		public boolean isSetRole() {
			return (this.role!= null);
		}

		/**
		 * Gets the value of the arcrole property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getArcrole() {
			return this.arcrole;
		}

		/**
		 * Sets the value of the arcrole property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setArcrole(String value) {
			this.arcrole = value;
		}

		public boolean isSetArcrole() {
			return (this.arcrole!= null);
		}

		/**
		 * Gets the value of the title property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getTitle() {
			return this.title;
		}

		/**
		 * Sets the value of the title property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setTitle(String value) {
			this.title = value;
		}

		public boolean isSetTitle() {
			return (this.title!= null);
		}

		/**
		 * Gets the value of the show property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getShow() {
			return this.show;
		}

		/**
		 * Sets the value of the show property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setShow(String value) {
			this.show = value;
		}

		public boolean isSetShow() {
			return (this.show!= null);
		}

		/**
		 * Gets the value of the actuate property.
		 * 
		 * @return
		 *     possible object is
		 *     {@link String }
		 * 
		 */
		public String getActuate() {
			return this.actuate;
		}

		/**
		 * Sets the value of the actuate property.
		 * 
		 * @param value
		 *     allowed object is
		 *     {@link String }
		 * 
		 */
		public void setActuate(String value) {
			this.actuate = value;
		}

		public boolean isSetActuate() {
			return (this.actuate!= null);
		}

		@Override
		public Object createNewInstance() {
			// TODO Auto-generated method stub
			return null;
		}

	}


	@Override
	public Object createNewInstance() {
		// TODO Auto-generated method stub
		return null;
	}

}
