//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.02 at 09:31:38 AM MESZ 
//


package playground.florian.jaxb.scores01;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the playground.florian.jaxb.scores01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: playground.florian.jaxb.scores01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLScores }
     * 
     */
    public XMLScores createXMLScores() {
        return new XMLScores();
    }

    /**
     * Create an instance of {@link XMLScoreType }
     * 
     */
    public XMLScoreType createXMLScoreType() {
        return new XMLScoreType();
    }

}
