//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.07.02 at 09:31:38 AM MESZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.matsim.org/files/dtd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package playground.florian.jaxb.scores01;
