// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/Frame.proto

package playground.gregor.proto;

public final class ProtoFrame {
  private ProtoFrame() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FrameOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Frame)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required double time = 1;</code>
     */
    double getTime();

    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    java.util.List<playground.gregor.proto.ProtoFrame.Frame.Event> 
        getEvntList();
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    playground.gregor.proto.ProtoFrame.Frame.Event getEvnt(int index);
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    int getEvntCount();
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    java.util.List<? extends playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder> 
        getEvntOrBuilderList();
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder getEvntOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Frame}
   */
  public static final class Frame extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Frame)
      FrameOrBuilder {
    // Use Frame.newBuilder() to construct.
    private Frame(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Frame(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Frame defaultInstance;
    public static Frame getDefaultInstance() {
      return defaultInstance;
    }

    public Frame getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Frame(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              time_ = input.readDouble();
              break;
            }
            case 130: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                evnt_ = new java.util.ArrayList<playground.gregor.proto.ProtoFrame.Frame.Event>();
                mutable_bitField0_ |= 0x00000002;
              }
              evnt_.add(input.readMessage(playground.gregor.proto.ProtoFrame.Frame.Event.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          evnt_ = java.util.Collections.unmodifiableList(evnt_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return playground.gregor.proto.ProtoFrame.internal_static_Frame_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return playground.gregor.proto.ProtoFrame.internal_static_Frame_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              playground.gregor.proto.ProtoFrame.Frame.class, playground.gregor.proto.ProtoFrame.Frame.Builder.class);
    }

    public static com.google.protobuf.Parser<Frame> PARSER =
        new com.google.protobuf.AbstractParser<Frame>() {
      public Frame parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Frame(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Frame> getParserForType() {
      return PARSER;
    }

    public interface EventOrBuilder extends
        // @@protoc_insertion_point(interface_extends:Frame.Event)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
       */
      boolean hasEvntType();
      /**
       * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
       */
      playground.gregor.proto.ProtoFrame.Frame.Event.Type getEvntType();
    }
    /**
     * Protobuf type {@code Frame.Event}
     */
    public static final class Event extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:Frame.Event)
        EventOrBuilder {
      // Use Event.newBuilder() to construct.
      private Event(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private Event(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final Event defaultInstance;
      public static Event getDefaultInstance() {
        return defaultInstance;
      }

      public Event getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private Event(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();
                playground.gregor.proto.ProtoFrame.Frame.Event.Type value = playground.gregor.proto.ProtoFrame.Frame.Event.Type.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(1, rawValue);
                } else {
                  bitField0_ |= 0x00000001;
                  evntType_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return playground.gregor.proto.ProtoFrame.internal_static_Frame_Event_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return playground.gregor.proto.ProtoFrame.internal_static_Frame_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                playground.gregor.proto.ProtoFrame.Frame.Event.class, playground.gregor.proto.ProtoFrame.Frame.Event.Builder.class);
      }

      public static com.google.protobuf.Parser<Event> PARSER =
          new com.google.protobuf.AbstractParser<Event>() {
        public Event parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Event(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Event> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code Frame.Event.Type}
       */
      public enum Type
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>POS = 0;</code>
         */
        POS(0, 0),
        /**
         * <code>LINK_INF = 1;</code>
         */
        LINK_INF(1, 1),
        ;

        /**
         * <code>POS = 0;</code>
         */
        public static final int POS_VALUE = 0;
        /**
         * <code>LINK_INF = 1;</code>
         */
        public static final int LINK_INF_VALUE = 1;


        public final int getNumber() { return value; }

        public static Type valueOf(int value) {
          switch (value) {
            case 0: return POS;
            case 1: return LINK_INF;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                public Type findValueByNumber(int number) {
                  return Type.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return playground.gregor.proto.ProtoFrame.Frame.Event.getDescriptor().getEnumTypes().get(0);
        }

        private static final Type[] VALUES = values();

        public static Type valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private Type(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:Frame.Event.Type)
      }

      private int bitField0_;
      public static final int EVNTTYPE_FIELD_NUMBER = 1;
      private playground.gregor.proto.ProtoFrame.Frame.Event.Type evntType_;
      /**
       * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
       */
      public boolean hasEvntType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
       */
      public playground.gregor.proto.ProtoFrame.Frame.Event.Type getEvntType() {
        return evntType_;
      }

      private void initFields() {
        evntType_ = playground.gregor.proto.ProtoFrame.Frame.Event.Type.POS;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeEnum(1, evntType_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(1, evntType_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static playground.gregor.proto.ProtoFrame.Frame.Event parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(playground.gregor.proto.ProtoFrame.Frame.Event prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code Frame.Event}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:Frame.Event)
          playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return playground.gregor.proto.ProtoFrame.internal_static_Frame_Event_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return playground.gregor.proto.ProtoFrame.internal_static_Frame_Event_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  playground.gregor.proto.ProtoFrame.Frame.Event.class, playground.gregor.proto.ProtoFrame.Frame.Event.Builder.class);
        }

        // Construct using playground.gregor.proto.ProtoFrame.Frame.Event.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          evntType_ = playground.gregor.proto.ProtoFrame.Frame.Event.Type.POS;
          bitField0_ = (bitField0_ & ~0x00000001);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return playground.gregor.proto.ProtoFrame.internal_static_Frame_Event_descriptor;
        }

        public playground.gregor.proto.ProtoFrame.Frame.Event getDefaultInstanceForType() {
          return playground.gregor.proto.ProtoFrame.Frame.Event.getDefaultInstance();
        }

        public playground.gregor.proto.ProtoFrame.Frame.Event build() {
          playground.gregor.proto.ProtoFrame.Frame.Event result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public playground.gregor.proto.ProtoFrame.Frame.Event buildPartial() {
          playground.gregor.proto.ProtoFrame.Frame.Event result = new playground.gregor.proto.ProtoFrame.Frame.Event(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.evntType_ = evntType_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof playground.gregor.proto.ProtoFrame.Frame.Event) {
            return mergeFrom((playground.gregor.proto.ProtoFrame.Frame.Event)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(playground.gregor.proto.ProtoFrame.Frame.Event other) {
          if (other == playground.gregor.proto.ProtoFrame.Frame.Event.getDefaultInstance()) return this;
          if (other.hasEvntType()) {
            setEvntType(other.getEvntType());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          playground.gregor.proto.ProtoFrame.Frame.Event parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (playground.gregor.proto.ProtoFrame.Frame.Event) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private playground.gregor.proto.ProtoFrame.Frame.Event.Type evntType_ = playground.gregor.proto.ProtoFrame.Frame.Event.Type.POS;
        /**
         * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
         */
        public boolean hasEvntType() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
         */
        public playground.gregor.proto.ProtoFrame.Frame.Event.Type getEvntType() {
          return evntType_;
        }
        /**
         * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
         */
        public Builder setEvntType(playground.gregor.proto.ProtoFrame.Frame.Event.Type value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000001;
          evntType_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .Frame.Event.Type evntType = 1 [default = POS];</code>
         */
        public Builder clearEvntType() {
          bitField0_ = (bitField0_ & ~0x00000001);
          evntType_ = playground.gregor.proto.ProtoFrame.Frame.Event.Type.POS;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:Frame.Event)
      }

      static {
        defaultInstance = new Event(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:Frame.Event)
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private double time_;
    /**
     * <code>required double time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double time = 1;</code>
     */
    public double getTime() {
      return time_;
    }

    public static final int EVNT_FIELD_NUMBER = 16;
    private java.util.List<playground.gregor.proto.ProtoFrame.Frame.Event> evnt_;
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    public java.util.List<playground.gregor.proto.ProtoFrame.Frame.Event> getEvntList() {
      return evnt_;
    }
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    public java.util.List<? extends playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder> 
        getEvntOrBuilderList() {
      return evnt_;
    }
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    public int getEvntCount() {
      return evnt_.size();
    }
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    public playground.gregor.proto.ProtoFrame.Frame.Event getEvnt(int index) {
      return evnt_.get(index);
    }
    /**
     * <code>repeated .Frame.Event evnt = 16;</code>
     */
    public playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder getEvntOrBuilder(
        int index) {
      return evnt_.get(index);
    }

    private void initFields() {
      time_ = 0D;
      evnt_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, time_);
      }
      for (int i = 0; i < evnt_.size(); i++) {
        output.writeMessage(16, evnt_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, time_);
      }
      for (int i = 0; i < evnt_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, evnt_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static playground.gregor.proto.ProtoFrame.Frame parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(playground.gregor.proto.ProtoFrame.Frame prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Frame}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Frame)
        playground.gregor.proto.ProtoFrame.FrameOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return playground.gregor.proto.ProtoFrame.internal_static_Frame_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return playground.gregor.proto.ProtoFrame.internal_static_Frame_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                playground.gregor.proto.ProtoFrame.Frame.class, playground.gregor.proto.ProtoFrame.Frame.Builder.class);
      }

      // Construct using playground.gregor.proto.ProtoFrame.Frame.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getEvntFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        time_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (evntBuilder_ == null) {
          evnt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          evntBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return playground.gregor.proto.ProtoFrame.internal_static_Frame_descriptor;
      }

      public playground.gregor.proto.ProtoFrame.Frame getDefaultInstanceForType() {
        return playground.gregor.proto.ProtoFrame.Frame.getDefaultInstance();
      }

      public playground.gregor.proto.ProtoFrame.Frame build() {
        playground.gregor.proto.ProtoFrame.Frame result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public playground.gregor.proto.ProtoFrame.Frame buildPartial() {
        playground.gregor.proto.ProtoFrame.Frame result = new playground.gregor.proto.ProtoFrame.Frame(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (evntBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            evnt_ = java.util.Collections.unmodifiableList(evnt_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.evnt_ = evnt_;
        } else {
          result.evnt_ = evntBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof playground.gregor.proto.ProtoFrame.Frame) {
          return mergeFrom((playground.gregor.proto.ProtoFrame.Frame)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(playground.gregor.proto.ProtoFrame.Frame other) {
        if (other == playground.gregor.proto.ProtoFrame.Frame.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (evntBuilder_ == null) {
          if (!other.evnt_.isEmpty()) {
            if (evnt_.isEmpty()) {
              evnt_ = other.evnt_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureEvntIsMutable();
              evnt_.addAll(other.evnt_);
            }
            onChanged();
          }
        } else {
          if (!other.evnt_.isEmpty()) {
            if (evntBuilder_.isEmpty()) {
              evntBuilder_.dispose();
              evntBuilder_ = null;
              evnt_ = other.evnt_;
              bitField0_ = (bitField0_ & ~0x00000002);
              evntBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getEvntFieldBuilder() : null;
            } else {
              evntBuilder_.addAllMessages(other.evnt_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        playground.gregor.proto.ProtoFrame.Frame parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (playground.gregor.proto.ProtoFrame.Frame) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double time_ ;
      /**
       * <code>required double time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double time = 1;</code>
       */
      public double getTime() {
        return time_;
      }
      /**
       * <code>required double time = 1;</code>
       */
      public Builder setTime(double value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0D;
        onChanged();
        return this;
      }

      private java.util.List<playground.gregor.proto.ProtoFrame.Frame.Event> evnt_ =
        java.util.Collections.emptyList();
      private void ensureEvntIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          evnt_ = new java.util.ArrayList<playground.gregor.proto.ProtoFrame.Frame.Event>(evnt_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          playground.gregor.proto.ProtoFrame.Frame.Event, playground.gregor.proto.ProtoFrame.Frame.Event.Builder, playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder> evntBuilder_;

      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public java.util.List<playground.gregor.proto.ProtoFrame.Frame.Event> getEvntList() {
        if (evntBuilder_ == null) {
          return java.util.Collections.unmodifiableList(evnt_);
        } else {
          return evntBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public int getEvntCount() {
        if (evntBuilder_ == null) {
          return evnt_.size();
        } else {
          return evntBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public playground.gregor.proto.ProtoFrame.Frame.Event getEvnt(int index) {
        if (evntBuilder_ == null) {
          return evnt_.get(index);
        } else {
          return evntBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder setEvnt(
          int index, playground.gregor.proto.ProtoFrame.Frame.Event value) {
        if (evntBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvntIsMutable();
          evnt_.set(index, value);
          onChanged();
        } else {
          evntBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder setEvnt(
          int index, playground.gregor.proto.ProtoFrame.Frame.Event.Builder builderForValue) {
        if (evntBuilder_ == null) {
          ensureEvntIsMutable();
          evnt_.set(index, builderForValue.build());
          onChanged();
        } else {
          evntBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder addEvnt(playground.gregor.proto.ProtoFrame.Frame.Event value) {
        if (evntBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvntIsMutable();
          evnt_.add(value);
          onChanged();
        } else {
          evntBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder addEvnt(
          int index, playground.gregor.proto.ProtoFrame.Frame.Event value) {
        if (evntBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureEvntIsMutable();
          evnt_.add(index, value);
          onChanged();
        } else {
          evntBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder addEvnt(
          playground.gregor.proto.ProtoFrame.Frame.Event.Builder builderForValue) {
        if (evntBuilder_ == null) {
          ensureEvntIsMutable();
          evnt_.add(builderForValue.build());
          onChanged();
        } else {
          evntBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder addEvnt(
          int index, playground.gregor.proto.ProtoFrame.Frame.Event.Builder builderForValue) {
        if (evntBuilder_ == null) {
          ensureEvntIsMutable();
          evnt_.add(index, builderForValue.build());
          onChanged();
        } else {
          evntBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder addAllEvnt(
          java.lang.Iterable<? extends playground.gregor.proto.ProtoFrame.Frame.Event> values) {
        if (evntBuilder_ == null) {
          ensureEvntIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, evnt_);
          onChanged();
        } else {
          evntBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder clearEvnt() {
        if (evntBuilder_ == null) {
          evnt_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          evntBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public Builder removeEvnt(int index) {
        if (evntBuilder_ == null) {
          ensureEvntIsMutable();
          evnt_.remove(index);
          onChanged();
        } else {
          evntBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public playground.gregor.proto.ProtoFrame.Frame.Event.Builder getEvntBuilder(
          int index) {
        return getEvntFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder getEvntOrBuilder(
          int index) {
        if (evntBuilder_ == null) {
          return evnt_.get(index);  } else {
          return evntBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public java.util.List<? extends playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder> 
           getEvntOrBuilderList() {
        if (evntBuilder_ != null) {
          return evntBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(evnt_);
        }
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public playground.gregor.proto.ProtoFrame.Frame.Event.Builder addEvntBuilder() {
        return getEvntFieldBuilder().addBuilder(
            playground.gregor.proto.ProtoFrame.Frame.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public playground.gregor.proto.ProtoFrame.Frame.Event.Builder addEvntBuilder(
          int index) {
        return getEvntFieldBuilder().addBuilder(
            index, playground.gregor.proto.ProtoFrame.Frame.Event.getDefaultInstance());
      }
      /**
       * <code>repeated .Frame.Event evnt = 16;</code>
       */
      public java.util.List<playground.gregor.proto.ProtoFrame.Frame.Event.Builder> 
           getEvntBuilderList() {
        return getEvntFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          playground.gregor.proto.ProtoFrame.Frame.Event, playground.gregor.proto.ProtoFrame.Frame.Event.Builder, playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder> 
          getEvntFieldBuilder() {
        if (evntBuilder_ == null) {
          evntBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              playground.gregor.proto.ProtoFrame.Frame.Event, playground.gregor.proto.ProtoFrame.Frame.Event.Builder, playground.gregor.proto.ProtoFrame.Frame.EventOrBuilder>(
                  evnt_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          evnt_ = null;
        }
        return evntBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:Frame)
    }

    static {
      defaultInstance = new Frame(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Frame)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Frame_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Frame_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Frame_Event_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Frame_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto/Frame.proto\"\203\001\n\005Frame\022\014\n\004time\030\001 " +
      "\002(\001\022\032\n\004evnt\030\020 \003(\0132\014.Frame.Event\032P\n\005Event" +
      "\022(\n\010evntType\030\001 \001(\0162\021.Frame.Event.Type:\003P" +
      "OS\"\035\n\004Type\022\007\n\003POS\020\000\022\014\n\010LINK_INF\020\001B%\n\027pla" +
      "yground.gregor.protoB\nProtoFrame"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Frame_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Frame_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Frame_descriptor,
        new java.lang.String[] { "Time", "Evnt", });
    internal_static_Frame_Event_descriptor =
      internal_static_Frame_descriptor.getNestedTypes().get(0);
    internal_static_Frame_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Frame_Event_descriptor,
        new java.lang.String[] { "EvntType", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
