//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.01 at 04:42:06 PM CEST 
//


package playground.gregor.grips.jaxb.EDL001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import playground.gregor.grips.jaxb.gml.AbstractGeometryType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the playground.gregor.grips.jaxb.EDL001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _XMLLinksBasedNetworkLinkTypeGeometry_QNAME = new QName("http://matsim.svn.sourceforge.net/viewvc/matsim/playgrounds/trunk/gregor/xsd", "geometry");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: playground.gregor.grips.jaxb.EDL001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link XMLMember }
     * 
     */
    public XMLMember createXMLMember() {
        return new XMLMember();
    }

    /**
     * Create an instance of {@link XMLUser }
     * 
     */
    public XMLUser createXMLUser() {
        return new XMLUser();
    }

    /**
     * Create an instance of {@link XMLEvacuationAreaType }
     * 
     */
    public XMLEvacuationAreaType createXMLEvacuationAreaType() {
        return new XMLEvacuationAreaType();
    }

    /**
     * Create an instance of {@link XMLApi }
     * 
     */
    public XMLApi createXMLApi() {
        return new XMLApi();
    }

    /**
     * Create an instance of {@link XMLLinksAndNodesBasedNetworkLinkType }
     * 
     */
    public XMLLinksAndNodesBasedNetworkLinkType createXMLLinksAndNodesBasedNetworkLinkType() {
        return new XMLLinksAndNodesBasedNetworkLinkType();
    }

    /**
     * Create an instance of {@link XMLHome }
     * 
     */
    public XMLHome createXMLHome() {
        return new XMLHome();
    }

    /**
     * Create an instance of {@link XMLPreferences }
     * 
     */
    public XMLPreferences createXMLPreferences() {
        return new XMLPreferences();
    }

    /**
     * Create an instance of {@link XMLNode }
     * 
     */
    public XMLNode createXMLNode() {
        return new XMLNode();
    }

    /**
     * Create an instance of {@link XMLPopulationType }
     * 
     */
    public XMLPopulationType createXMLPopulationType() {
        return new XMLPopulationType();
    }

    /**
     * Create an instance of {@link XMLVersion }
     * 
     */
    public XMLVersion createXMLVersion() {
        return new XMLVersion();
    }

    /**
     * Create an instance of {@link XMLLinksAndNodesBasedNetworkType }
     * 
     */
    public XMLLinksAndNodesBasedNetworkType createXMLLinksAndNodesBasedNetworkType() {
        return new XMLLinksAndNodesBasedNetworkType();
    }

    /**
     * Create an instance of {@link XMLLinksAndNodesBasedNetworkNodesType }
     * 
     */
    public XMLLinksAndNodesBasedNetworkNodesType createXMLLinksAndNodesBasedNetworkNodesType() {
        return new XMLLinksAndNodesBasedNetworkNodesType();
    }

    /**
     * Create an instance of {@link XMLChangeset }
     * 
     */
    public XMLChangeset createXMLChangeset() {
        return new XMLChangeset();
    }

    /**
     * Create an instance of {@link XMLLinksBasedNetworkType }
     * 
     */
    public XMLLinksBasedNetworkType createXMLLinksBasedNetworkType() {
        return new XMLLinksBasedNetworkType();
    }

    /**
     * Create an instance of {@link XMLTracepoints }
     * 
     */
    public XMLTracepoints createXMLTracepoints() {
        return new XMLTracepoints();
    }

    /**
     * Create an instance of {@link XMLLinksBasedNetworkLinksType }
     * 
     */
    public XMLLinksBasedNetworkLinksType createXMLLinksBasedNetworkLinksType() {
        return new XMLLinksBasedNetworkLinksType();
    }

    /**
     * Create an instance of {@link XMLEPSGCodeSRSType }
     * 
     */
    public XMLEPSGCodeSRSType createXMLEPSGCodeSRSType() {
        return new XMLEPSGCodeSRSType();
    }

    /**
     * Create an instance of {@link XMLOsm }
     * 
     */
    public XMLOsm createXMLOsm() {
        return new XMLOsm();
    }

    /**
     * Create an instance of {@link XMLRelation }
     * 
     */
    public XMLRelation createXMLRelation() {
        return new XMLRelation();
    }

    /**
     * Create an instance of {@link XMLSRSType }
     * 
     */
    public XMLSRSType createXMLSRSType() {
        return new XMLSRSType();
    }

    /**
     * Create an instance of {@link XMLLinksAndNodesBasedNetworkNodeType }
     * 
     */
    public XMLLinksAndNodesBasedNetworkNodeType createXMLLinksAndNodesBasedNetworkNodeType() {
        return new XMLLinksAndNodesBasedNetworkNodeType();
    }

    /**
     * Create an instance of {@link XMLGpxFile }
     * 
     */
    public XMLGpxFile createXMLGpxFile() {
        return new XMLGpxFile();
    }

    /**
     * Create an instance of {@link XMLLinksBasedNetworkLinkType }
     * 
     */
    public XMLLinksBasedNetworkLinkType createXMLLinksBasedNetworkLinkType() {
        return new XMLLinksBasedNetworkLinkType();
    }

    /**
     * Create an instance of {@link XMLNd }
     * 
     */
    public XMLNd createXMLNd() {
        return new XMLNd();
    }

    /**
     * Create an instance of {@link XMLArea }
     * 
     */
    public XMLArea createXMLArea() {
        return new XMLArea();
    }

    /**
     * Create an instance of {@link XMLEDL }
     * 
     */
    public XMLEDL createXMLEDL() {
        return new XMLEDL();
    }

    /**
     * Create an instance of {@link XMLTag }
     * 
     */
    public XMLTag createXMLTag() {
        return new XMLTag();
    }

    /**
     * Create an instance of {@link XMLWaynodes }
     * 
     */
    public XMLWaynodes createXMLWaynodes() {
        return new XMLWaynodes();
    }

    /**
     * Create an instance of {@link XMLWay }
     * 
     */
    public XMLWay createXMLWay() {
        return new XMLWay();
    }

    /**
     * Create an instance of {@link XMLOsmBasedNetworkType }
     * 
     */
    public XMLOsmBasedNetworkType createXMLOsmBasedNetworkType() {
        return new XMLOsmBasedNetworkType();
    }

    /**
     * Create an instance of {@link XMLLinksAndNodesBasedNetworkLinksType }
     * 
     */
    public XMLLinksAndNodesBasedNetworkLinksType createXMLLinksAndNodesBasedNetworkLinksType() {
        return new XMLLinksAndNodesBasedNetworkLinksType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractGeometryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://matsim.svn.sourceforge.net/viewvc/matsim/playgrounds/trunk/gregor/xsd", name = "geometry", scope = XMLLinksBasedNetworkLinkType.class)
    public JAXBElement<AbstractGeometryType> createXMLLinksBasedNetworkLinkTypeGeometry(AbstractGeometryType value) {
        return new JAXBElement<AbstractGeometryType>(_XMLLinksBasedNetworkLinkTypeGeometry_QNAME, AbstractGeometryType.class, XMLLinksBasedNetworkLinkType.class, value);
    }

}
