//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.07.29 at 11:10:31 AM CEST 
//


package playground.gregor.grips.jaxb.EDL001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for linksType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="linksType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="fromNodeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="toNodeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "linksType", propOrder = {
    "id",
    "fromNodeId",
    "toNodeId"
})
public class XMLLinksType {

    @XmlElement(name = "Id")
    protected int id;
    protected int fromNodeId;
    protected int toNodeId;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the fromNodeId property.
     * 
     */
    public int getFromNodeId() {
        return fromNodeId;
    }

    /**
     * Sets the value of the fromNodeId property.
     * 
     */
    public void setFromNodeId(int value) {
        this.fromNodeId = value;
    }

    /**
     * Gets the value of the toNodeId property.
     * 
     */
    public int getToNodeId() {
        return toNodeId;
    }

    /**
     * Sets the value of the toNodeId property.
     * 
     */
    public void setToNodeId(int value) {
        this.toNodeId = value;
    }

}
