//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.01 at 04:42:06 PM CEST 
//


package playground.gregor.grips.jaxb.EDL001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for osmBasedNetworkType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="osmBasedNetworkType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://matsim.svn.sourceforge.net/viewvc/matsim/playgrounds/trunk/gregor/xsd}osm"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "osmBasedNetworkType", propOrder = {
    "osm"
})
public class XMLOsmBasedNetworkType {

    @XmlElement(required = true)
    protected XMLOsm osm;

    /**
     * Gets the value of the osm property.
     * 
     * @return
     *     possible object is
     *     {@link XMLOsm }
     *     
     */
    public XMLOsm getOsm() {
        return osm;
    }

    /**
     * Sets the value of the osm property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLOsm }
     *     
     */
    public void setOsm(XMLOsm value) {
        this.osm = value;
    }

}
