//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.11.28 at 11:36:45 AM CET 
//


package org.matsim.contrib.grips.io.jaxb.gripsconfig;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for distributionType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="distributionType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="normal"/>
 *     &lt;enumeration value="log-normal"/>
 *     &lt;enumeration value="dirac-delta"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "distributionType")
@XmlEnum
public enum DistributionType {

    @XmlEnumValue("normal")
    NORMAL("normal"),
    @XmlEnumValue("log-normal")
    LOG_NORMAL("log-normal"),
    @XmlEnumValue("dirac-delta")
    DIRAC_DELTA("dirac-delta");
    private final String value;

    DistributionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DistributionType fromValue(String v) {
        for (DistributionType c: DistributionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
