package org.matsim.contrib.bicycle.network;

import org.matsim.api.core.v01.TransportMode;
import org.matsim.api.core.v01.network.Link;
import org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.Direction;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Applies bicycle-specific link attributes and access rules on top of the
 * generic network produced by {@link org.matsim.contrib.osm.networkReader.OsmBicycleReader}.
 *
 * <p>Intended to be plugged into the reader via
 * {@code .setAfterLinkCreated(policy::apply)}. For each freshly created link
 * this class:
 * <ol>
 *   <li>optionally copies selected raw OSM tags onto the link (via {@link TagCopy}),</li>
 *   <li>classifies the link's cycling infrastructure with {@link BicycleInfraClassifier}
 *       and writes it to the link attribute {@code bicycle_infra},</li>
 *   <li>enforces footway/pedestrian whitelist: bike is only allowed when the OSM
 *       tags explicitly permit it,</li>
 *   <li>kills links tagged {@code bicycle=no},</li>
 *   <li>cleans up bicycle-oneway links on path/cycleway/footway.</li>
 * </ol>
 * "Kill" here means the link stays in the graph but has no allowed modes and
 * zero capacity — this is easier for downstream simplifiers than physically
 * removing it.
 */
public final class BicycleLinkPolicy {

	public static final String BICYCLE_MODE = TransportMode.bike;

	private final BicycleInfraClassifier classifier;
	private final TagCopy tagCopy;

	public BicycleLinkPolicy(BicycleInfraClassifier classifier, TagCopy tagCopy) {
		this.classifier = classifier;
		this.tagCopy = tagCopy;
	}

	public void apply(Link link, Map<String, String> tags, Direction direction) {

		// 0. copy selected raw OSM tags onto the link (no-op if TagCopy has no keys)
		tagCopy.copy(link, tags);

		// 1. classify cycling infrastructure
		String infra = classifier.classify(tags, direction);
		link.getAttributes().putAttribute("bicycle_infra", infra);

		// 2. footway/pedestrian whitelist — kills the link if bike isn't explicitly allowed
		enforceFootwayPedestrianWhitelist(link, tags);
		if (link.getAllowedModes().isEmpty()) return;

		// 3. bicycle=no -> kill
		if ("no".equals(tags.get("bicycle"))) {
			kill(link);
			return;
		}

		// 4. oneway cleaning on path/cycleway/footway:
		//    the "_bike-reverse" link generated by the reader gets killed,
		//    the plain "r" reverse link loses the bike mode.
		if (isBicycleOnewayRelevant(tags)) {
			if (link.getId().toString().endsWith("r")) {
				removeMode(link, BICYCLE_MODE);
			}
			if (link.getId().toString().endsWith("_bike-reverse")) {
				kill(link);
			}
		}
	}

	// ------------------------------------------------------------------------

	private static void enforceFootwayPedestrianWhitelist(Link link, Map<String, String> tags) {
		String h = tags.get("highway");
		if (!("footway".equals(h) || "pedestrian".equals(h))) return;

		String bicycle = tags.get("bicycle");
		boolean ok = "yes".equals(bicycle) || "designated".equals(bicycle);
		if (!ok) {
			kill(link);
		}
	}

	private static void kill(Link link) {
		link.setAllowedModes(Set.of());
		link.setCapacity(0);
	}

	private static void removeMode(Link link, String mode) {
		var modes = new HashSet<>(link.getAllowedModes());
		modes.remove(mode);
		link.setAllowedModes(modes);
	}

	private static boolean isBicycleOnewayRelevant(Map<String, String> tags) {
		String h = tags.get("highway");
		boolean relevant = "path".equals(h) || "cycleway".equals(h) || "footway".equals(h);
		if (!relevant) return false;

		if ("yes".equals(tags.get("oneway:bicycle"))) return true;
		if ("yes".equals(tags.get("oneway"))) {
			return !"no".equals(tags.get("oneway:bicycle"));
		}
		return false;
	}
}
