/* *********************************************************************** *
 * project: org.matsim.*												   *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2008 by the members listed in the COPYING,        *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */
package org.matsim.contrib.bicycle.network;

import org.matsim.api.core.v01.TransportMode;
import org.matsim.api.core.v01.network.Link;
import org.matsim.contrib.osm.networkReader.SupersonicOsmNetworkReader.Direction;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

import static org.matsim.contrib.bicycle.network.BicycleNetworkPipeline.LINK_ATTR_BICYCLE_INFRA;
import static org.matsim.contrib.bicycle.network.BicycleOsmTags.*;

/**
 * Applies bicycle-specific link attributes and access rules on top of the
 * generic network produced by {@link org.matsim.contrib.osm.networkReader.OsmBicycleReader}.
 *
 * <p>Intended to be plugged into the reader via
 * {@code .setAfterLinkCreated(policy::apply)}. For each freshly created link
 * this class:
 * <ol>
 *   <li>optionally copies selected raw OSM tags onto the link (via {@link TagCopy}),</li>
 *   <li>classifies the link's cycling infrastructure with {@link BicycleInfraClassifier}
 *       and writes it to the link attribute
 *       {@link BicycleNetworkPipeline#LINK_ATTR_BICYCLE_INFRA},</li>
 *   <li>enforces footway/pedestrian whitelist: bike is only allowed when the OSM
 *       tags explicitly permit it,</li>
 *   <li>kills links tagged {@code bicycle=no},</li>
 *   <li>kills links whose general {@code access} is restricted
 *       ({@code no} / {@code private} / {@code customer}), unless a bicycle-specific
 *       tag ({@code bicycle=yes} / {@code =designated}) overrides it,</li>
 *   <li>cleans up bicycle-oneway links on path/cycleway/footway.</li>
 * </ol>
 * "Kill" here means the link stays in the graph but has no allowed modes and
 * zero capacity — this is easier for downstream simplifiers than physically
 * removing it.
 *
 * @author smetzler, esarikaya
 */
public final class BicycleLinkPolicy {

	private static final String BICYCLE_MODE = TransportMode.bike;

	private final BicycleInfraClassifier classifier;
	private final TagCopy tagCopy;

	public BicycleLinkPolicy(BicycleInfraClassifier classifier, TagCopy tagCopy) {
		this.classifier = classifier;
		this.tagCopy = tagCopy;
	}

	public void apply(Link link, Map<String, String> tags, Direction direction) {

		// 0. copy selected raw OSM tags onto the link (no-op if TagCopy has no keys)
		tagCopy.copy(link, tags);

		// 1. classify cycling infrastructure
		BicycleInfraCategory infra = classifier.classify(tags, direction);
		link.getAttributes().putAttribute(LINK_ATTR_BICYCLE_INFRA, infra.name());

		// 2. footway/pedestrian whitelist — kills the link if bike isn't explicitly allowed
		enforceFootwayPedestrianWhitelist(link, tags);
		if (link.getAllowedModes().isEmpty()) return;

		// 3. bicycle=no -> kill
		if (NO.equals(tags.get(BICYCLE))) {
			kill(link);
			return;
		}

		// 4. access=no/private/customer -> kill
		if (isAccessRestricted(tags)) {
			kill(link);
			return;
		}

		// 5. oneway cleaning on path/cycleway/footway:
		//    the "_bike-reverse" link generated by the reader gets killed,
		//    the plain "r" reverse link loses the bike mode.
		if (isBicycleOnewayRelevant(tags)) {
			if (link.getId().toString().endsWith("r")) {
				removeMode(link, BICYCLE_MODE);
			}
			if (link.getId().toString().endsWith("_bike-reverse")) {
				kill(link);
			}
		}
	}

	// ------------------------------------------------------------------------

	private static void enforceFootwayPedestrianWhitelist(Link link, Map<String, String> tags) {
		String highway = tags.get(HIGHWAY);
		if (!(HW_FOOTWAY.equals(highway) || HW_PEDESTRIAN.equals(highway))) return;

		if (!bicycleExplicitlyAllowed(tags)) {
			kill(link);
		}
	}

	/**
	 * Whether the OSM tags carry a bicycle-specific permission that grants cycling
	 * over a more general restriction — the footway/pedestrian default, or a
	 * restricted {@code access} (OSM: the more specific tag wins). Only
	 * {@code bicycle=yes} / {@code =designated} count for now; we might want to
	 * keep {@code bicycle=permissive} / {@code =dismount} as well.
	 */
	private static boolean bicycleExplicitlyAllowed(Map<String, String> tags) {
		String bicycle = tags.get(BICYCLE);
		return YES.equals(bicycle) || DESIGNATED.equals(bicycle);
	}

	private static boolean isAccessRestricted(Map<String, String> tags) {
		// Null-safe: raw OSM tag maps usually have no access key. Constant on the
		// left to avoid an NPE.
		String access = tags.get(ACCESS);
		boolean restricted = NO.equals(access) || PRIVATE.equals(access) || CUSTOMER.equals(access);
		// A bicycle-specific permission overrides the general access restriction,
		// e.g. access=private + bicycle=designated stays cyclable.
		return restricted && !bicycleExplicitlyAllowed(tags);
	}

	private static void kill(Link link) {
		link.setAllowedModes(Set.of());
		link.setCapacity(0);
	}

	private static void removeMode(Link link, String mode) {
		var modes = new HashSet<>(link.getAllowedModes());
		modes.remove(mode);
		link.setAllowedModes(modes);
	}

	private static boolean isBicycleOnewayRelevant(Map<String, String> tags) {
		String highway = tags.get(HIGHWAY);
		boolean relevant = HW_PATH.equals(highway) || HW_CYCLEWAY.equals(highway) || HW_FOOTWAY.equals(highway);
		if (!relevant) return false;

		// Null-safe: the tag map is the raw OSM tag set, so oneway / oneway:bicycle
		// are usually absent. Keep the constant on the left to avoid an NPE.
		if (YES.equals(tags.get(ONEWAY_BICYCLE))) return true;
		if (YES.equals(tags.get(ONEWAY))) {
			return !NO.equals(tags.get(ONEWAY_BICYCLE));
		}
		return false;
	}
}
