//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-520 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.03.09 at 05:29:45 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.matsim.org/files/dtd", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.matsim.jaxb.signalsystemsconfig11;
