//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 12:45:10 PM CEST 
//


package org.matsim.contrib.matsim4urbansim.matsim4urbansim.jaxbconfig2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for matsim4urbansimType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="matsim4urbansimType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="urbansimParameter" type="{}urbansimParameterType"/>
 *         &lt;element name="matsim4urbansimContoler" type="{}matsim4urbansimContolerType"/>
 *         &lt;element name="accessibilityParameter" type="{}accessibilityParameterType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "matsim4urbansimType", propOrder = {
    "urbansimParameter",
    "matsim4UrbansimContoler",
    "accessibilityParameter"
})
public class Matsim4UrbansimType {

    @XmlElement(required = true)
    protected UrbansimParameterType urbansimParameter;
    @XmlElement(name = "matsim4urbansimContoler", required = true)
    protected Matsim4UrbansimContolerType matsim4UrbansimContoler;
    @XmlElement(required = true)
    protected AccessibilityParameterType accessibilityParameter;

    /**
     * Gets the value of the urbansimParameter property.
     * 
     * @return
     *     possible object is
     *     {@link UrbansimParameterType }
     *     
     */
    public UrbansimParameterType getUrbansimParameter() {
        return urbansimParameter;
    }

    /**
     * Sets the value of the urbansimParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link UrbansimParameterType }
     *     
     */
    public void setUrbansimParameter(UrbansimParameterType value) {
        this.urbansimParameter = value;
    }

    /**
     * Gets the value of the matsim4UrbansimContoler property.
     * 
     * @return
     *     possible object is
     *     {@link Matsim4UrbansimContolerType }
     *     
     */
    public Matsim4UrbansimContolerType getMatsim4UrbansimContoler() {
        return matsim4UrbansimContoler;
    }

    /**
     * Sets the value of the matsim4UrbansimContoler property.
     * 
     * @param value
     *     allowed object is
     *     {@link Matsim4UrbansimContolerType }
     *     
     */
    public void setMatsim4UrbansimContoler(Matsim4UrbansimContolerType value) {
        this.matsim4UrbansimContoler = value;
    }

    /**
     * Gets the value of the accessibilityParameter property.
     * 
     * @return
     *     possible object is
     *     {@link AccessibilityParameterType }
     *     
     */
    public AccessibilityParameterType getAccessibilityParameter() {
        return accessibilityParameter;
    }

    /**
     * Sets the value of the accessibilityParameter property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccessibilityParameterType }
     *     
     */
    public void setAccessibilityParameter(AccessibilityParameterType value) {
        this.accessibilityParameter = value;
    }

}
