//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.04.19 at 12:45:10 PM CEST 
//


package org.matsim.contrib.matsim4urbansim.matsim4urbansim.jaxbconfig2;

import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


///**
// * <p>Java class for strategyType complex type.
// * 
// * <p>The following schema fragment specifies the expected content contained within this class.
// * 
// * <pre>
// * &lt;complexType name="strategyType">
// *   &lt;complexContent>
// *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
// *       &lt;sequence>
// *         &lt;element name="maxAgentPlanMemorySize" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
// *         &lt;element name="timeAllocationMutatorProbability" type="{http://www.w3.org/2001/XMLSchema}double"/>
// *         &lt;element name="changeExpBetaProbability" type="{http://www.w3.org/2001/XMLSchema}double"/>
// *         &lt;element name="reRouteDijkstraProbability" type="{http://www.w3.org/2001/XMLSchema}double"/>
// *       &lt;/sequence>
// *     &lt;/restriction>
// *   &lt;/complexContent>
// * &lt;/complexType>
// * </pre>
// * 
// * 
// */
//@XmlAccessorType(XmlAccessType.FIELD)
//@XmlType(name = "strategyType", propOrder = {
//    "maxAgentPlanMemorySize",
//    "timeAllocationMutatorProbability",
//    "changeExpBetaProbability",
//    "reRouteDijkstraProbability"
//})
public class StrategyType {

//    @XmlElement(required = true)
//    @XmlSchemaType(name = "nonNegativeInteger")
//    protected BigInteger maxAgentPlanMemorySize;
//    protected double timeAllocationMutatorProbability;
//    protected double changeExpBetaProbability;
//    protected double reRouteDijkstraProbability;

//    /**
//     * Gets the value of the maxAgentPlanMemorySize property.
//     * 
//     * @return
//     *     possible object is
//     *     {@link BigInteger }
//     *     
//     */
//    public BigInteger getMaxAgentPlanMemorySize() {
//        return maxAgentPlanMemorySize;
//    }

//    /**
//     * Sets the value of the maxAgentPlanMemorySize property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link BigInteger }
//     *     
//     */
//    public void setMaxAgentPlanMemorySize(BigInteger value) {
//        this.maxAgentPlanMemorySize = value;
//    }
//
//    /**
//     * Gets the value of the timeAllocationMutatorProbability property.
//     * 
//     */
//    public double getTimeAllocationMutatorProbability() {
//        return timeAllocationMutatorProbability;
//    }
//
//    /**
//     * Sets the value of the timeAllocationMutatorProbability property.
//     * 
//     */
//    public void setTimeAllocationMutatorProbability(double value) {
//        this.timeAllocationMutatorProbability = value;
//    }
//
//    /**
//     * Gets the value of the changeExpBetaProbability property.
//     * 
//     */
//    public double getChangeExpBetaProbability() {
//        return changeExpBetaProbability;
//    }
//
//    /**
//     * Sets the value of the changeExpBetaProbability property.
//     * 
//     */
//    public void setChangeExpBetaProbability(double value) {
//        this.changeExpBetaProbability = value;
//    }
//
//    /**
//     * Gets the value of the reRouteDijkstraProbability property.
//     * 
//     */
//    public double getReRouteDijkstraProbability() {
//        return reRouteDijkstraProbability;
//    }
//
//    /**
//     * Sets the value of the reRouteDijkstraProbability property.
//     * 
//     */
//    public void setReRouteDijkstraProbability(double value) {
//        this.reRouteDijkstraProbability = value;
//    }
//
}
