/* *********************************************************************** *
 * project: org.matsim.*
 * VolumesAnalyzer.java
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2007 by the members listed in the COPYING,        *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */

package org.matsim.analysis;

import com.google.inject.Inject;
import it.unimi.dsi.fastutil.ints.Int2ObjectMap;
import it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.matsim.api.core.v01.Id;
import org.matsim.api.core.v01.events.LinkLeaveEvent;
import org.matsim.api.core.v01.events.VehicleEntersTrafficEvent;
import org.matsim.api.core.v01.events.handler.AggregatingEventHandler;
import org.matsim.api.core.v01.events.handler.DistributedEventHandler;
import org.matsim.api.core.v01.events.handler.DistributedMode;
import org.matsim.api.core.v01.events.handler.LinkLeaveEventHandler;
import org.matsim.api.core.v01.events.handler.ProcessingMode;
import org.matsim.api.core.v01.events.handler.VehicleEntersTrafficEventHandler;
import org.matsim.api.core.v01.network.Link;
import org.matsim.api.core.v01.network.Network;
import org.matsim.core.api.experimental.events.EventsManager;
import org.matsim.core.mobsim.dsim.DistributedMobsimVehicle;
import org.matsim.core.mobsim.dsim.NotifyVehiclePartitionTransfer;
import org.matsim.core.mobsim.qsim.components.QSimComponent;
import org.matsim.vehicles.Vehicle;

import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.stream.IntStream;

/**
 * Counts the number of vehicles leaving a link, aggregated into time bins of a specified size.
 * I.e., this does not scale the counts by the PCU.
 * <p>
 * In a distributed simulation, the handler is called concurrently by all partitions of a node. This is safe, because
 * link leave events of one link are always generated by the same partition, and the arrays holding the volumes are
 * sized in {@link #reset(int)} before the simulation, so that they are not resized concurrently. Volumes of other
 * nodes are merged after the simulation.
 * <p>
 * With multiple compute nodes, vehicles may enter traffic on another node. The mode of such vehicles is taken from their
 * driver when they enter a partition, for which the analyzer is registered as simulation component.
 *
 * @author mrieser
 */
@DistributedEventHandler(value = DistributedMode.NODE_CONCURRENT, processing = ProcessingMode.DIRECT)
public class VolumesAnalyzer implements LinkLeaveEventHandler, VehicleEntersTrafficEventHandler,
	AggregatingEventHandler<VolumesSyncMessage>, NotifyVehiclePartitionTransfer, QSimComponent {

	private final static Logger log = LogManager.getLogger(VolumesAnalyzer.class);
	private final int timeBinSize;
	private final int maxTime;
	private final int maxSlotIndex;

	/**
	 * Volumes indexed by link id index.
	 */
	private int[][] links;

	// for multi-modal support
	private final boolean observeModes;

	/**
	 * Network mode of each vehicle, updated whenever a vehicle enters traffic.
	 */
	private final Map<Id<Vehicle>, String> enRouteModes = new ConcurrentHashMap<>();

	/**
	 * Volumes per mode indexed by link id index.
	 */
	private Map<String, int[]>[] linksPerMode;

	/**
	 * View on the ids of links with volumes, always reading the current {@link #links} array.
	 */
	private final Set<Id<Link>> linkIds = new AbstractSet<>() {
		@Override
		public boolean contains(Object o) {
			int[][] links = VolumesAnalyzer.this.links;
			return o instanceof Id<?> id && id.index() < links.length && links[id.index()] != null;
		}

		@Override
		public Iterator<Id<Link>> iterator() {
			int[][] links = VolumesAnalyzer.this.links;
			return IntStream.range(0, links.length)
				.filter(i -> links[i] != null)
				.mapToObj(i -> Id.get(i, Link.class))
				.iterator();
		}

		@Override
		public int size() {
			return (int) Arrays.stream(VolumesAnalyzer.this.links).filter(Objects::nonNull).count();
		}
	};

	@Inject
	VolumesAnalyzer(Network network, EventsManager eventsManager) {
		this(3600, 24 * 3600 - 1, network);
		eventsManager.addHandler(this);
	}

	public VolumesAnalyzer(final int timeBinSize, final int maxTime, final Network network) {
		this(timeBinSize, maxTime, network, true);
	}

	public VolumesAnalyzer(final int timeBinSize, final int maxTime, final Network network, boolean observeModes) {
		this.timeBinSize = timeBinSize;
		this.maxTime = maxTime;
		this.maxSlotIndex = (this.maxTime / this.timeBinSize) + 1;
		this.observeModes = observeModes;
		clear();
	}

	@SuppressWarnings("unchecked")
	private void clear() {
		int numLinks = Id.getNumberOfIds(Link.class);
		this.links = new int[numLinks][];
		if (this.observeModes) {
			this.linksPerMode = new Map[numLinks];
			this.enRouteModes.clear();
		}
	}

	/**
	 * Grow arrays for link ids created after the last reset. This is not thread-safe, but does not happen during a
	 * distributed simulation, where all links exist before the simulation starts.
	 */
	private void ensureLinkCapacity(int index) {
		if (index >= this.links.length) {
			int size = Math.max(index + 1, Id.getNumberOfIds(Link.class));
			this.links = Arrays.copyOf(this.links, size);
			if (this.observeModes) {
				this.linksPerMode = Arrays.copyOf(this.linksPerMode, size);
			}
		}
	}

	@Override
	public void handleEvent(VehicleEntersTrafficEvent event) {
		setEnRouteMode(event.getVehicleId(), event.getNetworkMode());
	}

	/**
	 * Vehicles coming from another compute node did not enter traffic on this node. The driver provides the same mode
	 * as the {@link VehicleEntersTrafficEvent}.
	 */
	@Override
	public void onVehicleEntersPartition(DistributedMobsimVehicle vehicle) {
		setEnRouteMode(vehicle.getId(), vehicle.getDriver().getMode());
	}

	@Override
	public void onVehicleLeavesPartition(DistributedMobsimVehicle vehicle, int toPartition) {
	}

	private void setEnRouteMode(Id<Vehicle> vehicleId, String mode) {
		if (this.observeModes) {
			if (mode != null) {
				this.enRouteModes.put(vehicleId, mode);
			} else {
				this.enRouteModes.remove(vehicleId);
			}
		}
	}

	@Override
	public void handleEvent(final LinkLeaveEvent event) {
		int index = event.getLinkId().index();
		ensureLinkCapacity(index);

		int[] volumes = this.links[index];
		if (volumes == null) {
			volumes = new int[this.maxSlotIndex + 1]; // initialized to 0 by default, according to JVM specs
			this.links[index] = volumes;
		}
		int timeslot = getTimeSlotIndex(event.getTime());
		volumes[timeslot]++;

		if (this.observeModes) {
			Map<String, int[]> modeVolumes = this.linksPerMode[index];
			if (modeVolumes == null) {
				modeVolumes = new HashMap<>();
				this.linksPerMode[index] = modeVolumes;
			}
			String mode = this.enRouteModes.get(event.getVehicleId());
			volumes = modeVolumes.get(mode);
			if (volumes == null) {
				volumes = new int[this.maxSlotIndex + 1]; // initialized to 0 by default, according to JVM specs
				modeVolumes.put(mode, volumes);
			}
			volumes[timeslot]++;
		}
	}

	private int getTimeSlotIndex(final double time) {
		if (time > this.maxTime) {
			return this.maxSlotIndex;
		}
		return ((int) time / this.timeBinSize);
	}

	/**
	 * @param linkId
	 * @return Array containing the number of vehicles leaving the link <code>linkId</code> per time bin,
	 * starting with time bin 0 from 0 seconds to (timeBinSize-1)seconds.
	 */
	public int[] getVolumesForLink(final Id<Link> linkId) {
		int index = linkId.index();
		return index < this.links.length ? this.links[index] : null;
	}

	/**
	 * @param linkId
	 * @param mode
	 * @return Array containing the number of vehicles using the specified mode leaving the link
	 * <code>linkId</code> per time bin, starting with time bin 0 from 0 seconds to (timeBinSize-1)seconds.
	 */
	public int[] getVolumesForLink(final Id<Link> linkId, String mode) {
		if (observeModes && linkId.index() < this.linksPerMode.length) {
			Map<String, int[]> modeVolumes = this.linksPerMode[linkId.index()];
			if (modeVolumes != null) return modeVolumes.get(mode);
		}
		return null;
	}

	/**
	 * @return The size of the arrays returned by calls to the {@link #getVolumesForLink(Id)} and the {@link #getVolumesForLink(Id, String)}
	 * methods.
	 */
	public int getVolumesArraySize() {
		return this.maxSlotIndex + 1;
	}

	/*
	 * This procedure is only working if (hour % timeBinSize == 0)
	 *
	 * Example: 15 minutes bins
	 *  ___________________
	 * |  0 | 1  | 2  | 3  |
	 * |____|____|____|____|
	 * 0   900 1800  2700 3600
		___________________
	 * | 	  hour 0	   |
	 * |___________________|
	 * 0   				  3600
	 *
	 * hour 0 = bins 0,1,2,3
	 * hour 1 = bins 4,5,6,7
	 * ...
	 *
	 * getTimeSlotIndex = (int)time / this.timeBinSize => jumps at 3600.0!
	 * Thus, starting time = (hour = 0) * 3600.0
	 */
	public double[] getVolumesPerHourForLink(final Id<Link> linkId) {
		if (3600.0 % this.timeBinSize != 0) log.error("Volumes per hour and per link probably not correct!");

		double[] volumes = new double[24];

		int[] volumesForLink = this.getVolumesForLink(linkId);
		if (volumesForLink == null) return volumes;

		int slotsPerHour = (int) (3600.0 / this.timeBinSize);
		for (int hour = 0; hour < 24; hour++) {
			double time = hour * 3600.0;
			for (int i = 0; i < slotsPerHour; i++) {
				volumes[hour] += volumesForLink[this.getTimeSlotIndex(time)];
				time += this.timeBinSize;
			}
		}
		return volumes;
	}

	public double[] getVolumesPerHourForLink(final Id<Link> linkId, String mode) {
		if (observeModes) {
			if (3600.0 % this.timeBinSize != 0) log.error("Volumes per hour and per link probably not correct!");

			double[] volumes = new double[24];
			for (int hour = 0; hour < 24; hour++) {
				volumes[hour] = 0.0;
			}

			int[] volumesForLink = this.getVolumesForLink(linkId, mode);
			if (volumesForLink == null) return volumes;

			int slotsPerHour = (int) (3600.0 / this.timeBinSize);
			for (int hour = 0; hour < 24; hour++) {
				double time = hour * 3600.0;
				for (int i = 0; i < slotsPerHour; i++) {
					volumes[hour] += volumesForLink[this.getTimeSlotIndex(time)];
					time += this.timeBinSize;
				}
			}
			return volumes;
		}
		return null;
	}

	/**
	 * @return Set of Strings containing all modes for which counting-values are available.
	 */
	public Set<String> getModes() {
		Set<String> modes = new TreeSet<>();
		if (!observeModes) return modes;

		for (Map<String, int[]> map : this.linksPerMode) {
			if (map == null) continue;
			try {
				modes.addAll(map.keySet());
			} catch (NullPointerException ex) {
				// Fails on initialized entries, which can happen during tests
				// will just be ignored here
			}
		}

		return modes;
	}

	/**
	 * @return Set of Strings containing all link ids for which counting-values are available. The set is a view, so
	 * lookups are cheap, e.g. within loops over all links.
	 */
	public Set<Id<Link>> getLinkIds() {
		return this.linkIds;
	}

	@Override
	public void reset(final int iteration) {
		clear();
	}

	/**
	 * Volumes are only needed after the simulation, so they are only exchanged once after the simulation has finished.
	 */
	@Override
	public double getSyncInterval() {
		return Double.POSITIVE_INFINITY;
	}

	@Override
	public VolumesSyncMessage send() {
		VolumesSyncMessage msg = new VolumesSyncMessage();
		for (int i = 0; i < this.links.length; i++) {
			if (this.links[i] != null) {
				msg.volumes.put(i, this.links[i]);
			}
			if (this.observeModes && this.linksPerMode[i] != null) {
				for (Map.Entry<String, int[]> e : this.linksPerMode[i].entrySet()) {
					if (e.getKey() != null) {
						msg.modeVolumes.computeIfAbsent(e.getKey(), k -> new Int2ObjectOpenHashMap<>()).put(i, e.getValue());
					}
				}
			}
		}
		return msg;
	}

	/**
	 * Each link is only counted on the node owning it. Volumes are only taken over for links without own volumes, which
	 * makes receiving idempotent, e.g. if the own message is received as well.
	 */
	@Override
	public void receive(List<VolumesSyncMessage> messages) {
		for (VolumesSyncMessage msg : messages) {
			for (Int2ObjectMap.Entry<int[]> e : msg.volumes.int2ObjectEntrySet()) {
				ensureLinkCapacity(e.getIntKey());
				if (this.links[e.getIntKey()] == null) {
					this.links[e.getIntKey()] = e.getValue().clone();
				}
			}

			if (!this.observeModes) continue;

			for (Map.Entry<String, Int2ObjectMap<int[]>> modes : msg.modeVolumes.entrySet()) {
				for (Int2ObjectMap.Entry<int[]> e : modes.getValue().int2ObjectEntrySet()) {
					ensureLinkCapacity(e.getIntKey());
					Map<String, int[]> modeVolumes = this.linksPerMode[e.getIntKey()];
					if (modeVolumes == null) {
						modeVolumes = new HashMap<>();
						this.linksPerMode[e.getIntKey()] = modeVolumes;
					}
					modeVolumes.putIfAbsent(modes.getKey(), e.getValue().clone());
				}
			}
		}
	}
}
