//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 02:05:46 PM CEST 
//


package playground.gregor.grips.jaxb.inspire.roadtransportnetwork;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import net.opengis.gml.v_3_2_1.TimePeriodPropertyType;
import playground.gregor.grips.jaxb.inspire.geographicalnames.GeographicalNamePropertyType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the playground.gregor.grips.jaxb.inspire.roadtransportnetwork package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RoadServiceArea_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadServiceArea");
    private final static QName _RoadWidth_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadWidth");
    private final static QName _ERoad_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "ERoad");
    private final static QName _SpeedLimit_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "SpeedLimit");
    private final static QName _Road_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "Road");
    private final static QName _RoadNode_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadNode");
    private final static QName _RoadSurfaceCategory_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadSurfaceCategory");
    private final static QName _RoadName_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadName");
    private final static QName _VehicleTrafficArea_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "VehicleTrafficArea");
    private final static QName _RoadLink_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadLink");
    private final static QName _FormOfWay_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "FormOfWay");
    private final static QName _RoadLinkSequence_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadLinkSequence");
    private final static QName _RoadServiceType_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadServiceType");
    private final static QName _NumberOfLanes_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "NumberOfLanes");
    private final static QName _RoadArea_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "RoadArea");
    private final static QName _FunctionalRoadClass_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "FunctionalRoadClass");
    private final static QName _NumberOfLanesTypeMinMaxNumberOfLanes_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "minMaxNumberOfLanes");
    private final static QName _NumberOfLanesTypeDirection_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "direction");
    private final static QName _RoadNameTypeName_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "name");
    private final static QName _SpeedLimitTypeVehicleType_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "vehicleType");
    private final static QName _SpeedLimitTypeLaneExtension_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "laneExtension");
    private final static QName _SpeedLimitTypeWeatherCondition_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "weatherCondition");
    private final static QName _SpeedLimitTypeStartLane_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "startLane");
    private final static QName _SpeedLimitTypeAreaCondition_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "areaCondition");
    private final static QName _SpeedLimitTypeSpeedLimitSource_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "speedLimitSource");
    private final static QName _SpeedLimitTypeValidityPeriod_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "validityPeriod");
    private final static QName _RoadTypeNationalRoadCode_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "nationalRoadCode");
    private final static QName _RoadTypeLocalRoadCode_QNAME = new QName("urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", "localRoadCode");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: playground.gregor.grips.jaxb.inspire.roadtransportnetwork
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RoadNodeType }
     * 
     */
    public RoadNodeType createRoadNodeType() {
        return new RoadNodeType();
    }

    /**
     * Create an instance of {@link NumberOfLanesPropertyType }
     * 
     */
    public NumberOfLanesPropertyType createNumberOfLanesPropertyType() {
        return new NumberOfLanesPropertyType();
    }

    /**
     * Create an instance of {@link NumberOfLanesType.Direction }
     * 
     */
    public NumberOfLanesType.Direction createNumberOfLanesTypeDirection() {
        return new NumberOfLanesType.Direction();
    }

    /**
     * Create an instance of {@link RoadWidthType }
     * 
     */
    public RoadWidthType createRoadWidthType() {
        return new RoadWidthType();
    }

    /**
     * Create an instance of {@link NumberOfLanesType }
     * 
     */
    public NumberOfLanesType createNumberOfLanesType() {
        return new NumberOfLanesType();
    }

    /**
     * Create an instance of {@link SpeedLimitType.Direction }
     * 
     */
    public SpeedLimitType.Direction createSpeedLimitTypeDirection() {
        return new SpeedLimitType.Direction();
    }

    /**
     * Create an instance of {@link RoadLinkSequencePropertyType }
     * 
     */
    public RoadLinkSequencePropertyType createRoadLinkSequencePropertyType() {
        return new RoadLinkSequencePropertyType();
    }

    /**
     * Create an instance of {@link SpeedLimitType.SpeedLimitSource }
     * 
     */
    public SpeedLimitType.SpeedLimitSource createSpeedLimitTypeSpeedLimitSource() {
        return new SpeedLimitType.SpeedLimitSource();
    }

    /**
     * Create an instance of {@link VehicleTrafficAreaPropertyType }
     * 
     */
    public VehicleTrafficAreaPropertyType createVehicleTrafficAreaPropertyType() {
        return new VehicleTrafficAreaPropertyType();
    }

    /**
     * Create an instance of {@link SpeedLimitType.LaneExtension }
     * 
     */
    public SpeedLimitType.LaneExtension createSpeedLimitTypeLaneExtension() {
        return new SpeedLimitType.LaneExtension();
    }

    /**
     * Create an instance of {@link RoadServiceTypeType }
     * 
     */
    public RoadServiceTypeType createRoadServiceTypeType() {
        return new RoadServiceTypeType();
    }

    /**
     * Create an instance of {@link ERoadType.EuropeanRouteNumber }
     * 
     */
    public ERoadType.EuropeanRouteNumber createERoadTypeEuropeanRouteNumber() {
        return new ERoadType.EuropeanRouteNumber();
    }

    /**
     * Create an instance of {@link RoadType.LocalRoadCode }
     * 
     */
    public RoadType.LocalRoadCode createRoadTypeLocalRoadCode() {
        return new RoadType.LocalRoadCode();
    }

    /**
     * Create an instance of {@link RoadWidthPropertyType }
     * 
     */
    public RoadWidthPropertyType createRoadWidthPropertyType() {
        return new RoadWidthPropertyType();
    }

    /**
     * Create an instance of {@link RoadServiceAreaType }
     * 
     */
    public RoadServiceAreaType createRoadServiceAreaType() {
        return new RoadServiceAreaType();
    }

    /**
     * Create an instance of {@link RoadSurfaceCategoryType }
     * 
     */
    public RoadSurfaceCategoryType createRoadSurfaceCategoryType() {
        return new RoadSurfaceCategoryType();
    }

    /**
     * Create an instance of {@link SpeedLimitType.StartLane }
     * 
     */
    public SpeedLimitType.StartLane createSpeedLimitTypeStartLane() {
        return new SpeedLimitType.StartLane();
    }

    /**
     * Create an instance of {@link RoadLinkSequenceType }
     * 
     */
    public RoadLinkSequenceType createRoadLinkSequenceType() {
        return new RoadLinkSequenceType();
    }

    /**
     * Create an instance of {@link RoadNameType }
     * 
     */
    public RoadNameType createRoadNameType() {
        return new RoadNameType();
    }

    /**
     * Create an instance of {@link RoadServiceAreaPropertyType }
     * 
     */
    public RoadServiceAreaPropertyType createRoadServiceAreaPropertyType() {
        return new RoadServiceAreaPropertyType();
    }

    /**
     * Create an instance of {@link FormOfWayPropertyType }
     * 
     */
    public FormOfWayPropertyType createFormOfWayPropertyType() {
        return new FormOfWayPropertyType();
    }

    /**
     * Create an instance of {@link VehicleTrafficAreaType }
     * 
     */
    public VehicleTrafficAreaType createVehicleTrafficAreaType() {
        return new VehicleTrafficAreaType();
    }

    /**
     * Create an instance of {@link RoadAreaPropertyType }
     * 
     */
    public RoadAreaPropertyType createRoadAreaPropertyType() {
        return new RoadAreaPropertyType();
    }

    /**
     * Create an instance of {@link RoadServiceTypePropertyType }
     * 
     */
    public RoadServiceTypePropertyType createRoadServiceTypePropertyType() {
        return new RoadServiceTypePropertyType();
    }

    /**
     * Create an instance of {@link FormOfWayType }
     * 
     */
    public FormOfWayType createFormOfWayType() {
        return new FormOfWayType();
    }

    /**
     * Create an instance of {@link RoadSurfaceCategoryPropertyType }
     * 
     */
    public RoadSurfaceCategoryPropertyType createRoadSurfaceCategoryPropertyType() {
        return new RoadSurfaceCategoryPropertyType();
    }

    /**
     * Create an instance of {@link RoadLinkType }
     * 
     */
    public RoadLinkType createRoadLinkType() {
        return new RoadLinkType();
    }

    /**
     * Create an instance of {@link SpeedLimitType }
     * 
     */
    public SpeedLimitType createSpeedLimitType() {
        return new SpeedLimitType();
    }

    /**
     * Create an instance of {@link RoadType }
     * 
     */
    public RoadType createRoadType() {
        return new RoadType();
    }

    /**
     * Create an instance of {@link SpeedLimitType.AreaCondition }
     * 
     */
    public SpeedLimitType.AreaCondition createSpeedLimitTypeAreaCondition() {
        return new SpeedLimitType.AreaCondition();
    }

    /**
     * Create an instance of {@link RoadAreaType }
     * 
     */
    public RoadAreaType createRoadAreaType() {
        return new RoadAreaType();
    }

    /**
     * Create an instance of {@link FunctionalRoadClassType }
     * 
     */
    public FunctionalRoadClassType createFunctionalRoadClassType() {
        return new FunctionalRoadClassType();
    }

    /**
     * Create an instance of {@link SpeedLimitType.WeatherCondition }
     * 
     */
    public SpeedLimitType.WeatherCondition createSpeedLimitTypeWeatherCondition() {
        return new SpeedLimitType.WeatherCondition();
    }

    /**
     * Create an instance of {@link RoadType.NationalRoadCode }
     * 
     */
    public RoadType.NationalRoadCode createRoadTypeNationalRoadCode() {
        return new RoadType.NationalRoadCode();
    }

    /**
     * Create an instance of {@link SpeedLimitType.VehicleType }
     * 
     */
    public SpeedLimitType.VehicleType createSpeedLimitTypeVehicleType() {
        return new SpeedLimitType.VehicleType();
    }

    /**
     * Create an instance of {@link RoadNodeType.FormOfRoadNode }
     * 
     */
    public RoadNodeType.FormOfRoadNode createRoadNodeTypeFormOfRoadNode() {
        return new RoadNodeType.FormOfRoadNode();
    }

    /**
     * Create an instance of {@link RoadNamePropertyType }
     * 
     */
    public RoadNamePropertyType createRoadNamePropertyType() {
        return new RoadNamePropertyType();
    }

    /**
     * Create an instance of {@link SpeedLimitPropertyType }
     * 
     */
    public SpeedLimitPropertyType createSpeedLimitPropertyType() {
        return new SpeedLimitPropertyType();
    }

    /**
     * Create an instance of {@link RoadLinkPropertyType }
     * 
     */
    public RoadLinkPropertyType createRoadLinkPropertyType() {
        return new RoadLinkPropertyType();
    }

    /**
     * Create an instance of {@link NumberOfLanesType.MinMaxNumberOfLanes }
     * 
     */
    public NumberOfLanesType.MinMaxNumberOfLanes createNumberOfLanesTypeMinMaxNumberOfLanes() {
        return new NumberOfLanesType.MinMaxNumberOfLanes();
    }

    /**
     * Create an instance of {@link ERoadPropertyType }
     * 
     */
    public ERoadPropertyType createERoadPropertyType() {
        return new ERoadPropertyType();
    }

    /**
     * Create an instance of {@link RoadNodePropertyType }
     * 
     */
    public RoadNodePropertyType createRoadNodePropertyType() {
        return new RoadNodePropertyType();
    }

    /**
     * Create an instance of {@link ERoadType }
     * 
     */
    public ERoadType createERoadType() {
        return new ERoadType();
    }

    /**
     * Create an instance of {@link RoadPropertyType }
     * 
     */
    public RoadPropertyType createRoadPropertyType() {
        return new RoadPropertyType();
    }

    /**
     * Create an instance of {@link RoadWidthType.MeasuredRoadPart }
     * 
     */
    public RoadWidthType.MeasuredRoadPart createRoadWidthTypeMeasuredRoadPart() {
        return new RoadWidthType.MeasuredRoadPart();
    }

    /**
     * Create an instance of {@link FunctionalRoadClassPropertyType }
     * 
     */
    public FunctionalRoadClassPropertyType createFunctionalRoadClassPropertyType() {
        return new FunctionalRoadClassPropertyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadServiceAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadServiceArea", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportArea")
    public JAXBElement<RoadServiceAreaType> createRoadServiceArea(RoadServiceAreaType value) {
        return new JAXBElement<RoadServiceAreaType>(_RoadServiceArea_QNAME, RoadServiceAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadWidthType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadWidth", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<RoadWidthType> createRoadWidth(RoadWidthType value) {
        return new JAXBElement<RoadWidthType>(_RoadWidth_QNAME, RoadWidthType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ERoadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "ERoad", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportLinkSet")
    public JAXBElement<ERoadType> createERoad(ERoadType value) {
        return new JAXBElement<ERoadType>(_ERoad_QNAME, ERoadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "SpeedLimit", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<SpeedLimitType> createSpeedLimit(SpeedLimitType value) {
        return new JAXBElement<SpeedLimitType>(_SpeedLimit_QNAME, SpeedLimitType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "Road", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportLinkSet")
    public JAXBElement<RoadType> createRoad(RoadType value) {
        return new JAXBElement<RoadType>(_Road_QNAME, RoadType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadNodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadNode", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportNode")
    public JAXBElement<RoadNodeType> createRoadNode(RoadNodeType value) {
        return new JAXBElement<RoadNodeType>(_RoadNode_QNAME, RoadNodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadSurfaceCategoryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadSurfaceCategory", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<RoadSurfaceCategoryType> createRoadSurfaceCategory(RoadSurfaceCategoryType value) {
        return new JAXBElement<RoadSurfaceCategoryType>(_RoadSurfaceCategory_QNAME, RoadSurfaceCategoryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadNameType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadName", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<RoadNameType> createRoadName(RoadNameType value) {
        return new JAXBElement<RoadNameType>(_RoadName_QNAME, RoadNameType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VehicleTrafficAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "VehicleTrafficArea", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportArea")
    public JAXBElement<VehicleTrafficAreaType> createVehicleTrafficArea(VehicleTrafficAreaType value) {
        return new JAXBElement<VehicleTrafficAreaType>(_VehicleTrafficArea_QNAME, VehicleTrafficAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadLinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadLink", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportLink")
    public JAXBElement<RoadLinkType> createRoadLink(RoadLinkType value) {
        return new JAXBElement<RoadLinkType>(_RoadLink_QNAME, RoadLinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormOfWayType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "FormOfWay", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<FormOfWayType> createFormOfWay(FormOfWayType value) {
        return new JAXBElement<FormOfWayType>(_FormOfWay_QNAME, FormOfWayType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadLinkSequenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadLinkSequence", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportLinkSequence")
    public JAXBElement<RoadLinkSequenceType> createRoadLinkSequence(RoadLinkSequenceType value) {
        return new JAXBElement<RoadLinkSequenceType>(_RoadLinkSequence_QNAME, RoadLinkSequenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadServiceTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadServiceType", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<RoadServiceTypeType> createRoadServiceType(RoadServiceTypeType value) {
        return new JAXBElement<RoadServiceTypeType>(_RoadServiceType_QNAME, RoadServiceTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberOfLanesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "NumberOfLanes", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<NumberOfLanesType> createNumberOfLanes(NumberOfLanesType value) {
        return new JAXBElement<NumberOfLanesType>(_NumberOfLanes_QNAME, NumberOfLanesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "RoadArea", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportArea")
    public JAXBElement<RoadAreaType> createRoadArea(RoadAreaType value) {
        return new JAXBElement<RoadAreaType>(_RoadArea_QNAME, RoadAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FunctionalRoadClassType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "FunctionalRoadClass", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:CommonTransportElements:3.0", substitutionHeadName = "TransportProperty")
    public JAXBElement<FunctionalRoadClassType> createFunctionalRoadClass(FunctionalRoadClassType value) {
        return new JAXBElement<FunctionalRoadClassType>(_FunctionalRoadClass_QNAME, FunctionalRoadClassType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberOfLanesType.MinMaxNumberOfLanes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "minMaxNumberOfLanes", scope = NumberOfLanesType.class)
    public JAXBElement<NumberOfLanesType.MinMaxNumberOfLanes> createNumberOfLanesTypeMinMaxNumberOfLanes(NumberOfLanesType.MinMaxNumberOfLanes value) {
        return new JAXBElement<NumberOfLanesType.MinMaxNumberOfLanes>(_NumberOfLanesTypeMinMaxNumberOfLanes_QNAME, NumberOfLanesType.MinMaxNumberOfLanes.class, NumberOfLanesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NumberOfLanesType.Direction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "direction", scope = NumberOfLanesType.class)
    public JAXBElement<NumberOfLanesType.Direction> createNumberOfLanesTypeDirection(NumberOfLanesType.Direction value) {
        return new JAXBElement<NumberOfLanesType.Direction>(_NumberOfLanesTypeDirection_QNAME, NumberOfLanesType.Direction.class, NumberOfLanesType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeographicalNamePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "name", scope = RoadNameType.class)
    public JAXBElement<GeographicalNamePropertyType> createRoadNameTypeName(GeographicalNamePropertyType value) {
        return new JAXBElement<GeographicalNamePropertyType>(_RoadNameTypeName_QNAME, GeographicalNamePropertyType.class, RoadNameType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.VehicleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "vehicleType", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.VehicleType> createSpeedLimitTypeVehicleType(SpeedLimitType.VehicleType value) {
        return new JAXBElement<SpeedLimitType.VehicleType>(_SpeedLimitTypeVehicleType_QNAME, SpeedLimitType.VehicleType.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.LaneExtension }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "laneExtension", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.LaneExtension> createSpeedLimitTypeLaneExtension(SpeedLimitType.LaneExtension value) {
        return new JAXBElement<SpeedLimitType.LaneExtension>(_SpeedLimitTypeLaneExtension_QNAME, SpeedLimitType.LaneExtension.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.WeatherCondition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "weatherCondition", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.WeatherCondition> createSpeedLimitTypeWeatherCondition(SpeedLimitType.WeatherCondition value) {
        return new JAXBElement<SpeedLimitType.WeatherCondition>(_SpeedLimitTypeWeatherCondition_QNAME, SpeedLimitType.WeatherCondition.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.StartLane }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "startLane", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.StartLane> createSpeedLimitTypeStartLane(SpeedLimitType.StartLane value) {
        return new JAXBElement<SpeedLimitType.StartLane>(_SpeedLimitTypeStartLane_QNAME, SpeedLimitType.StartLane.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.AreaCondition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "areaCondition", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.AreaCondition> createSpeedLimitTypeAreaCondition(SpeedLimitType.AreaCondition value) {
        return new JAXBElement<SpeedLimitType.AreaCondition>(_SpeedLimitTypeAreaCondition_QNAME, SpeedLimitType.AreaCondition.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.SpeedLimitSource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "speedLimitSource", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.SpeedLimitSource> createSpeedLimitTypeSpeedLimitSource(SpeedLimitType.SpeedLimitSource value) {
        return new JAXBElement<SpeedLimitType.SpeedLimitSource>(_SpeedLimitTypeSpeedLimitSource_QNAME, SpeedLimitType.SpeedLimitSource.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimePeriodPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "validityPeriod", scope = SpeedLimitType.class)
    public JAXBElement<TimePeriodPropertyType> createSpeedLimitTypeValidityPeriod(TimePeriodPropertyType value) {
        return new JAXBElement<TimePeriodPropertyType>(_SpeedLimitTypeValidityPeriod_QNAME, TimePeriodPropertyType.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpeedLimitType.Direction }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "direction", scope = SpeedLimitType.class)
    public JAXBElement<SpeedLimitType.Direction> createSpeedLimitTypeDirection(SpeedLimitType.Direction value) {
        return new JAXBElement<SpeedLimitType.Direction>(_NumberOfLanesTypeDirection_QNAME, SpeedLimitType.Direction.class, SpeedLimitType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadType.NationalRoadCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "nationalRoadCode", scope = RoadType.class)
    public JAXBElement<RoadType.NationalRoadCode> createRoadTypeNationalRoadCode(RoadType.NationalRoadCode value) {
        return new JAXBElement<RoadType.NationalRoadCode>(_RoadTypeNationalRoadCode_QNAME, RoadType.NationalRoadCode.class, RoadType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RoadType.LocalRoadCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:RoadTransportNetwork:3.0", name = "localRoadCode", scope = RoadType.class)
    public JAXBElement<RoadType.LocalRoadCode> createRoadTypeLocalRoadCode(RoadType.LocalRoadCode value) {
        return new JAXBElement<RoadType.LocalRoadCode>(_RoadTypeLocalRoadCode_QNAME, RoadType.LocalRoadCode.class, RoadType.class, value);
    }

}
