//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 02:05:46 PM CEST 
//


package playground.gregor.grips.jaxb.inspire.network;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DirectedLinkPropertyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DirectedLinkPropertyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{urn:x-inspire:specification:gmlas:Network:3.2}DirectedLink"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DirectedLinkPropertyType", propOrder = {
    "directedLink"
})
public class DirectedLinkPropertyType {

    @XmlElement(name = "DirectedLink", required = true)
    protected DirectedLinkType directedLink;

    /**
     * Gets the value of the directedLink property.
     * 
     * @return
     *     possible object is
     *     {@link DirectedLinkType }
     *     
     */
    public DirectedLinkType getDirectedLink() {
        return directedLink;
    }

    /**
     * Sets the value of the directedLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectedLinkType }
     *     
     */
    public void setDirectedLink(DirectedLinkType value) {
        this.directedLink = value;
    }

    public boolean isSetDirectedLink() {
        return (this.directedLink!= null);
    }

}
