//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.08.04 at 02:05:46 PM CEST 
//


package playground.gregor.grips.jaxb.inspire.network;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the playground.gregor.grips.jaxb.inspire.network package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _NetworkElement_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "NetworkElement");
    private final static QName _GeneralisedLink_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "GeneralisedLink");
    private final static QName _NetworkConnection_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "NetworkConnection");
    private final static QName _LinkSequence_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "LinkSequence");
    private final static QName _SimplePointReference_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "SimplePointReference");
    private final static QName _NetworkProperty_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "NetworkProperty");
    private final static QName _NetworkArea_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "NetworkArea");
    private final static QName _Network_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "Network");
    private final static QName _NetworkReference_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "NetworkReference");
    private final static QName _Node_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "Node");
    private final static QName _CrossReference_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "CrossReference");
    private final static QName _Link_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "Link");
    private final static QName _GradeSeparatedCrossing_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "GradeSeparatedCrossing");
    private final static QName _DirectedLink_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "DirectedLink");
    private final static QName _SimpleLinearReference_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "SimpleLinearReference");
    private final static QName _LinkSet_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "LinkSet");
    private final static QName _LinkReference_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "LinkReference");
    private final static QName _SimpleLinearReferenceTypeOffset_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "offset");
    private final static QName _NetworkPropertyTypeEndLifespanVersion_QNAME = new QName("urn:x-inspire:specification:gmlas:Network:3.2", "endLifespanVersion");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: playground.gregor.grips.jaxb.inspire.network
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LinkSequencePropertyType }
     * 
     */
    public LinkSequencePropertyType createLinkSequencePropertyType() {
        return new LinkSequencePropertyType();
    }

    /**
     * Create an instance of {@link LinkReferencePropertyType }
     * 
     */
    public LinkReferencePropertyType createLinkReferencePropertyType() {
        return new LinkReferencePropertyType();
    }

    /**
     * Create an instance of {@link CrossReferenceType }
     * 
     */
    public CrossReferenceType createCrossReferenceType() {
        return new CrossReferenceType();
    }

    /**
     * Create an instance of {@link CrossReferencePropertyType }
     * 
     */
    public CrossReferencePropertyType createCrossReferencePropertyType() {
        return new CrossReferencePropertyType();
    }

    /**
     * Create an instance of {@link NetworkType }
     * 
     */
    public NetworkType createNetworkType() {
        return new NetworkType();
    }

    /**
     * Create an instance of {@link GeneralisedLinkPropertyType }
     * 
     */
    public GeneralisedLinkPropertyType createGeneralisedLinkPropertyType() {
        return new GeneralisedLinkPropertyType();
    }

    /**
     * Create an instance of {@link NodePropertyType }
     * 
     */
    public NodePropertyType createNodePropertyType() {
        return new NodePropertyType();
    }

    /**
     * Create an instance of {@link SimpleLinearReferencePropertyType }
     * 
     */
    public SimpleLinearReferencePropertyType createSimpleLinearReferencePropertyType() {
        return new SimpleLinearReferencePropertyType();
    }

    /**
     * Create an instance of {@link NetworkConnectionType }
     * 
     */
    public NetworkConnectionType createNetworkConnectionType() {
        return new NetworkConnectionType();
    }

    /**
     * Create an instance of {@link NetworkPropertyType.NetworkRef }
     * 
     */
    public NetworkPropertyType.NetworkRef createNetworkPropertyTypeNetworkRef() {
        return new NetworkPropertyType.NetworkRef();
    }

    /**
     * Create an instance of {@link NetworkReferenceType }
     * 
     */
    public NetworkReferenceType createNetworkReferenceType() {
        return new NetworkReferenceType();
    }

    /**
     * Create an instance of {@link NetworkReferencePropertyType }
     * 
     */
    public NetworkReferencePropertyType createNetworkReferencePropertyType() {
        return new NetworkReferencePropertyType();
    }

    /**
     * Create an instance of {@link NetworkPropertyPropertyType }
     * 
     */
    public NetworkPropertyPropertyType createNetworkPropertyPropertyType() {
        return new NetworkPropertyPropertyType();
    }

    /**
     * Create an instance of {@link SimplePointReferenceType.Offset }
     * 
     */
    public SimplePointReferenceType.Offset createSimplePointReferenceTypeOffset() {
        return new SimplePointReferenceType.Offset();
    }

    /**
     * Create an instance of {@link LinkSetType.Link }
     * 
     */
    public LinkSetType.Link createLinkSetTypeLink() {
        return new LinkSetType.Link();
    }

    /**
     * Create an instance of {@link LinkReferenceType.ApplicableDirection }
     * 
     */
    public LinkReferenceType.ApplicableDirection createLinkReferenceTypeApplicableDirection() {
        return new LinkReferenceType.ApplicableDirection();
    }

    /**
     * Create an instance of {@link NetworkPropertyType.EndLifespanVersion }
     * 
     */
    public NetworkPropertyType.EndLifespanVersion createNetworkPropertyTypeEndLifespanVersion() {
        return new NetworkPropertyType.EndLifespanVersion();
    }

    /**
     * Create an instance of {@link SimpleLinearReferenceType.Offset }
     * 
     */
    public SimpleLinearReferenceType.Offset createSimpleLinearReferenceTypeOffset() {
        return new SimpleLinearReferenceType.Offset();
    }

    /**
     * Create an instance of {@link NetworkConnectionType.Type }
     * 
     */
    public NetworkConnectionType.Type createNetworkConnectionTypeType() {
        return new NetworkConnectionType.Type();
    }

    /**
     * Create an instance of {@link SimpleLinearReferenceType }
     * 
     */
    public SimpleLinearReferenceType createSimpleLinearReferenceType() {
        return new SimpleLinearReferenceType();
    }

    /**
     * Create an instance of {@link SimplePointReferenceType }
     * 
     */
    public SimplePointReferenceType createSimplePointReferenceType() {
        return new SimplePointReferenceType();
    }

    /**
     * Create an instance of {@link GradeSeparatedCrossingType }
     * 
     */
    public GradeSeparatedCrossingType createGradeSeparatedCrossingType() {
        return new GradeSeparatedCrossingType();
    }

    /**
     * Create an instance of {@link NetworkElementType.EndLifespanVersion }
     * 
     */
    public NetworkElementType.EndLifespanVersion createNetworkElementTypeEndLifespanVersion() {
        return new NetworkElementType.EndLifespanVersion();
    }

    /**
     * Create an instance of {@link NetworkPropertyType.BeginLifespanVersion }
     * 
     */
    public NetworkPropertyType.BeginLifespanVersion createNetworkPropertyTypeBeginLifespanVersion() {
        return new NetworkPropertyType.BeginLifespanVersion();
    }

    /**
     * Create an instance of {@link DirectedLinkType }
     * 
     */
    public DirectedLinkType createDirectedLinkType() {
        return new DirectedLinkType();
    }

    /**
     * Create an instance of {@link NetworkConnectionPropertyType }
     * 
     */
    public NetworkConnectionPropertyType createNetworkConnectionPropertyType() {
        return new NetworkConnectionPropertyType();
    }

    /**
     * Create an instance of {@link LinkReferenceType }
     * 
     */
    public LinkReferenceType createLinkReferenceType() {
        return new LinkReferenceType();
    }

    /**
     * Create an instance of {@link NetworkAreaPropertyType }
     * 
     */
    public NetworkAreaPropertyType createNetworkAreaPropertyType() {
        return new NetworkAreaPropertyType();
    }

    /**
     * Create an instance of {@link SimplePointReferencePropertyType }
     * 
     */
    public SimplePointReferencePropertyType createSimplePointReferencePropertyType() {
        return new SimplePointReferencePropertyType();
    }

    /**
     * Create an instance of {@link GradeSeparatedCrossingPropertyType }
     * 
     */
    public GradeSeparatedCrossingPropertyType createGradeSeparatedCrossingPropertyType() {
        return new GradeSeparatedCrossingPropertyType();
    }

    /**
     * Create an instance of {@link NetworkElementPropertyType }
     * 
     */
    public NetworkElementPropertyType createNetworkElementPropertyType() {
        return new NetworkElementPropertyType();
    }

    /**
     * Create an instance of {@link NetworkType.GeographicalName }
     * 
     */
    public NetworkType.GeographicalName createNetworkTypeGeographicalName() {
        return new NetworkType.GeographicalName();
    }

    /**
     * Create an instance of {@link DirectedLinkPropertyType }
     * 
     */
    public DirectedLinkPropertyType createDirectedLinkPropertyType() {
        return new DirectedLinkPropertyType();
    }

    /**
     * Create an instance of {@link NetworkElementType.BeginLifespanVersion }
     * 
     */
    public NetworkElementType.BeginLifespanVersion createNetworkElementTypeBeginLifespanVersion() {
        return new NetworkElementType.BeginLifespanVersion();
    }

    /**
     * Create an instance of {@link LinkSetPropertyType }
     * 
     */
    public LinkSetPropertyType createLinkSetPropertyType() {
        return new LinkSetPropertyType();
    }

    /**
     * Create an instance of {@link LinkPropertyType }
     * 
     */
    public LinkPropertyType createLinkPropertyType() {
        return new LinkPropertyType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkElementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "NetworkElement", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<NetworkElementType> createNetworkElement(NetworkElementType value) {
        return new JAXBElement<NetworkElementType>(_NetworkElement_QNAME, NetworkElementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneralisedLinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "GeneralisedLink", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkElement")
    public JAXBElement<GeneralisedLinkType> createGeneralisedLink(GeneralisedLinkType value) {
        return new JAXBElement<GeneralisedLinkType>(_GeneralisedLink_QNAME, GeneralisedLinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkConnectionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "NetworkConnection", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkElement")
    public JAXBElement<NetworkConnectionType> createNetworkConnection(NetworkConnectionType value) {
        return new JAXBElement<NetworkConnectionType>(_NetworkConnection_QNAME, NetworkConnectionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkSequenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "LinkSequence", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "GeneralisedLink")
    public JAXBElement<LinkSequenceType> createLinkSequence(LinkSequenceType value) {
        return new JAXBElement<LinkSequenceType>(_LinkSequence_QNAME, LinkSequenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimplePointReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "SimplePointReference", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "LinkReference")
    public JAXBElement<SimplePointReferenceType> createSimplePointReference(SimplePointReferenceType value) {
        return new JAXBElement<SimplePointReferenceType>(_SimplePointReference_QNAME, SimplePointReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "NetworkProperty", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<NetworkPropertyType> createNetworkProperty(NetworkPropertyType value) {
        return new JAXBElement<NetworkPropertyType>(_NetworkProperty_QNAME, NetworkPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkAreaType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "NetworkArea", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkElement")
    public JAXBElement<NetworkAreaType> createNetworkArea(NetworkAreaType value) {
        return new JAXBElement<NetworkAreaType>(_NetworkArea_QNAME, NetworkAreaType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "Network", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<NetworkType> createNetwork(NetworkType value) {
        return new JAXBElement<NetworkType>(_Network_QNAME, NetworkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "NetworkReference", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<NetworkReferenceType> createNetworkReference(NetworkReferenceType value) {
        return new JAXBElement<NetworkReferenceType>(_NetworkReference_QNAME, NetworkReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NodeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "Node", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkElement")
    public JAXBElement<NodeType> createNode(NodeType value) {
        return new JAXBElement<NodeType>(_Node_QNAME, NodeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrossReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "CrossReference", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<CrossReferenceType> createCrossReference(CrossReferenceType value) {
        return new JAXBElement<CrossReferenceType>(_CrossReference_QNAME, CrossReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "Link", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "GeneralisedLink")
    public JAXBElement<LinkType> createLink(LinkType value) {
        return new JAXBElement<LinkType>(_Link_QNAME, LinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GradeSeparatedCrossingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "GradeSeparatedCrossing", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkElement")
    public JAXBElement<GradeSeparatedCrossingType> createGradeSeparatedCrossing(GradeSeparatedCrossingType value) {
        return new JAXBElement<GradeSeparatedCrossingType>(_GradeSeparatedCrossing_QNAME, GradeSeparatedCrossingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectedLinkType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "DirectedLink", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<DirectedLinkType> createDirectedLink(DirectedLinkType value) {
        return new JAXBElement<DirectedLinkType>(_DirectedLink_QNAME, DirectedLinkType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLinearReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "SimpleLinearReference", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "LinkReference")
    public JAXBElement<SimpleLinearReferenceType> createSimpleLinearReference(SimpleLinearReferenceType value) {
        return new JAXBElement<SimpleLinearReferenceType>(_SimpleLinearReference_QNAME, SimpleLinearReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkSetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "LinkSet", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkElement")
    public JAXBElement<LinkSetType> createLinkSet(LinkSetType value) {
        return new JAXBElement<LinkSetType>(_LinkSet_QNAME, LinkSetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinkReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "LinkReference", substitutionHeadNamespace = "urn:x-inspire:specification:gmlas:Network:3.2", substitutionHeadName = "NetworkReference")
    public JAXBElement<LinkReferenceType> createLinkReference(LinkReferenceType value) {
        return new JAXBElement<LinkReferenceType>(_LinkReference_QNAME, LinkReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimpleLinearReferenceType.Offset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "offset", scope = SimpleLinearReferenceType.class)
    public JAXBElement<SimpleLinearReferenceType.Offset> createSimpleLinearReferenceTypeOffset(SimpleLinearReferenceType.Offset value) {
        return new JAXBElement<SimpleLinearReferenceType.Offset>(_SimpleLinearReferenceTypeOffset_QNAME, SimpleLinearReferenceType.Offset.class, SimpleLinearReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SimplePointReferenceType.Offset }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "offset", scope = SimplePointReferenceType.class)
    public JAXBElement<SimplePointReferenceType.Offset> createSimplePointReferenceTypeOffset(SimplePointReferenceType.Offset value) {
        return new JAXBElement<SimplePointReferenceType.Offset>(_SimpleLinearReferenceTypeOffset_QNAME, SimplePointReferenceType.Offset.class, SimplePointReferenceType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkPropertyType.EndLifespanVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "endLifespanVersion", scope = NetworkPropertyType.class)
    public JAXBElement<NetworkPropertyType.EndLifespanVersion> createNetworkPropertyTypeEndLifespanVersion(NetworkPropertyType.EndLifespanVersion value) {
        return new JAXBElement<NetworkPropertyType.EndLifespanVersion>(_NetworkPropertyTypeEndLifespanVersion_QNAME, NetworkPropertyType.EndLifespanVersion.class, NetworkPropertyType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NetworkElementType.EndLifespanVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:x-inspire:specification:gmlas:Network:3.2", name = "endLifespanVersion", scope = NetworkElementType.class)
    public JAXBElement<NetworkElementType.EndLifespanVersion> createNetworkElementTypeEndLifespanVersion(NetworkElementType.EndLifespanVersion value) {
        return new JAXBElement<NetworkElementType.EndLifespanVersion>(_NetworkPropertyTypeEndLifespanVersion_QNAME, NetworkElementType.EndLifespanVersion.class, NetworkElementType.class, value);
    }

}
