/* *********************************************************************** *
 * project: org.matsim.*
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2013 by the members listed in the COPYING,     *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */

package playground.southafrica.population.freight;

import org.matsim.core.gbl.MatsimRandom;

import playground.southafrica.freight.digicore.containers.DigicoreActivity;

/**
 * Class to sample the {@link DigicoreActivity} duration (in seconds).
 *
 * @author jwjoubert
 */
public class ActivityDuration {
	private final static double[] CUMULATIVE_PROBABILITY_2009 = {0.10, 0.20, 0.30, 0.40, 0.50,
																 0.60, 0.70, 0.80, 0.90, 1.00};
	private final static double[] DURATION_2009 = { 151,  267,  413,  613,   897, 
												   1326, 2053, 3487, 7449, 14297};
	
	/**
	 * Samples an activity duration from a preset cumulative probability
	 * distribution that was generated by analysing all the activity chains from
	 * observed Digicore vehicles.
	 *  
	 * @param random a random value in the range [0; 1].
	 * @return a start time (in seconds) within the range [00:00; 23:59].
	 */
	public static double getDurationInSeconds(double random){
		if(random < 0.0 && random > 1.0){
			throw new IllegalArgumentException("Given random number must be in the range [0; 1].");
		}
		
		return getLatestDurationInSeconds(random);
	}
	
	private static double getLatestDurationInSeconds(double random){
		double[] probs = CUMULATIVE_PROBABILITY_2009;
		double[] durations = DURATION_2009;
		
		Double duration = null;
		int index = 0;
		do {
			if(random <= probs[index]){
				if(index == 0){
					duration = new Double( MatsimRandom.getRandom().nextDouble()*durations[index] );
				} else{
					duration = new Double( durations[index-1] + MatsimRandom.getRandom().nextDouble()*(durations[index] - durations[index-1]) );
				}
			} else{
				index++;
			}
		} while (duration == null);
		return duration;
	}
															 
}