/* *********************************************************************** *
 * project: org.matsim.*
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2013 by the members listed in the COPYING,     *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */

/**
 * 
 */
package playground.southafrica.population.freight;

/**
 * Class to sample the number of activities per chain given a random number.
 * 
 * @author jwjoubert
 */

public class ChainActivities {
	private final static double[] CUMULATIVE_PROBABILITY_2009 = {0.1039, 0.1722, 0.2259, 0.2729, 0.3166, 
																 0.3588, 0.4005, 0.4420, 0.4829, 0.5229, 
																 0.5620, 0.5998, 0.6357, 0.6702, 0.7023, 
																 0.7324, 0.7600, 0.7853, 0.8086, 0.8295, 
																 0.8485, 0.8653, 0.8804, 0.8938, 0.9056, 
																 0.9159, 0.9249, 0.9329, 0.9399, 0.9460, 
																 0.9513, 0.9561, 0.9602, 0.9639, 0.9671, 
																 0.9699, 0.9724, 0.9747, 0.9768, 0.9786, 
																 0.9803, 0.9818, 0.9832, 0.9845, 0.9857, 
																 0.9868, 0.9877, 0.9887, 0.9896, 0.9904, 
																 0.9912, 0.9919, 0.9925, 0.9932, 0.9938, 
																 0.9944, 0.9949, 0.9954, 0.9958, 0.9963, 
																 0.9967, 0.9971, 0.9975, 0.9978, 0.9982, 
																 0.9985, 0.9988, 0.9991, 0.9994, 1.0000};
	
	/**
	 * Samples the number of activities in an activity chain from a preset 
	 * cumulative distribution that was generated by analysing all the 'normal
	 * weekday' activity chains from a training set sampled from the observed 
	 * Digicore vehicles.
	 *  
	 * @param random a random value in the range [0; 1].
	 * @return the number of activities per chain within the range [0; 69],
	 * 		   which is the 99th percentile.
	 */
	public static int getNumberOfActivities(double random){
		if(random < 0.0 && random > 1.0){
			throw new IllegalArgumentException("Given random number must be in the range [0; 1].");
		}
		
		double[] cumprob = CUMULATIVE_PROBABILITY_2009;
		Integer activities = null;
		int index = 0;
		do {
			if(cumprob[index] >= random){
				activities = index;
			} else{
				index++;
			}
		} while (activities == null);
		
		return activities;
	}
}
