//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.08.04 at 02:05:46 PM CEST
//


package playground.gregor.grips.jaxb.inspire.commontransportelements;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import playground.gregor.grips.jaxb.inspire.basetypes.VerticalPositionValueType;


/**
 * <p>Java class for VerticalPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerticalPositionType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:x-inspire:specification:gmlas:CommonTransportElements:3.0}TransportPropertyType">
 *       &lt;sequence>
 *         &lt;element name="verticalPosition" type="{urn:x-inspire:specification:gmlas:BaseTypes:3.2}VerticalPositionValueType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerticalPositionType", propOrder = {
		"verticalPosition"
})
public class VerticalPositionType
extends TransportPropertyType
{

	@XmlElement(required = true)
	protected VerticalPositionValueType verticalPosition;

	/**
	 * Gets the value of the verticalPosition property.
	 * 
	 * @return
	 *     possible object is
	 *     {@link VerticalPositionValueType }
	 * 
	 */
	public VerticalPositionValueType getVerticalPosition() {
		return this.verticalPosition;
	}

	/**
	 * Sets the value of the verticalPosition property.
	 * 
	 * @param value
	 *     allowed object is
	 *     {@link VerticalPositionValueType }
	 * 
	 */
	public void setVerticalPosition(VerticalPositionValueType value) {
		this.verticalPosition = value;
	}

	public boolean isSetVerticalPosition() {
		return (this.verticalPosition!= null);
	}

	@Override
	public Object createNewInstance() {
		// TODO Auto-generated method stub
		return null;
	}

}
