//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.09.27 at 04:03:56 PM CEST 
//


package playground.tnicolai.urbansim.com.matsim.config;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for urbansimParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="urbansimParameterType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="samplingRate" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="year" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger"/>
 *         &lt;element name="tempDirectory" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="isTestRun" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="opusHOME" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "urbansimParameterType", propOrder = {
    "samplingRate",
    "year",
    "tempDirectory",
    "isTestRun",
    "opusHOME"
})
public class UrbansimParameterType {

    protected double samplingRate;
    @XmlElement(required = true)
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger year;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String tempDirectory;
    protected boolean isTestRun;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String opusHOME;

    /**
     * Gets the value of the samplingRate property.
     * 
     */
    public double getSamplingRate() {
        return samplingRate;
    }

    /**
     * Sets the value of the samplingRate property.
     * 
     */
    public void setSamplingRate(double value) {
        this.samplingRate = value;
    }

    /**
     * Gets the value of the year property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getYear() {
        return year;
    }

    /**
     * Sets the value of the year property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setYear(BigInteger value) {
        this.year = value;
    }

    /**
     * Gets the value of the tempDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTempDirectory() {
        return tempDirectory;
    }

    /**
     * Sets the value of the tempDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTempDirectory(String value) {
        this.tempDirectory = value;
    }

    /**
     * Gets the value of the isTestRun property.
     * 
     */
    public boolean isIsTestRun() {
        return isTestRun;
    }

    /**
     * Sets the value of the isTestRun property.
     * 
     */
    public void setIsTestRun(boolean value) {
        this.isTestRun = value;
    }

    /**
     * Gets the value of the opusHOME property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpusHOME() {
        return opusHOME;
    }

    /**
     * Sets the value of the opusHOME property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpusHOME(String value) {
        this.opusHOME = value;
    }

}
