/* *********************************************************************** *
 * project: org.matsim.*
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 * copyright       : (C) 2023 by the members listed in the COPYING,        *
 *                   LICENSE and WARRANTY file.                            *
 * email           : info at matsim dot org                                *
 *                                                                         *
 * *********************************************************************** *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *   See also COPYING, LICENSE and WARRANTY file                           *
 *                                                                         *
 * *********************************************************************** */

package ch.sbb.matsim.contrib.railsim.config;

import org.matsim.core.config.ReflectiveConfigGroup;

public class RailsimConfigGroup extends ReflectiveConfigGroup {

	public final static String GROUP_NAME = "railsim";

	public RailsimConfigGroup() {
		super(GROUP_NAME);
	}

	// TODO: add config parameters
	// - "railNetworkModes", default "rail"
	// - "railVehicleModes", default "rail"(or "train"?)
	// - "linkEventsInterval", default "10", the iteration-interval when link-events should be generated by railsim
	// - "visualizationInterval", default "10", the iteration-interval when various csv-files should be generated used to visualize the results in Via

}
