name: weekly-code-coverage

on:
  workflow_dispatch:
  schedule:
    - cron: '30 3 * * 0' # Sun 3:30 UTC
  pull_request:
    paths:
      - '.github/workflows/code-coverage.yaml' # so that it also runs on PRs that change this file

jobs:
  code-coverage:
    name: create and publish coverage report

    runs-on: ubuntu-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'maven'

      # Run unit and integration tests for core with jacoco profile
      - name: Create coverage report
        run: mvn verify -P jacoco -pl matsim --batch-mode --also-make -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

      - name: Push core code coverage to CodeCov
        uses: codecov/codecov-action@v5
        with:
          files: ./matsim/target/site/jacoco/jacoco.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: core
          fail_ci_if_error: true

      # Prepare list of contrib modules to run tests on
      - name: Detect contrib modules (excluding _template)
        id: contribs
        run: |
          MODULES=$(find contribs -name pom.xml -exec dirname {} \; | grep -v 'contribs/_template' | paste -sd, -)
          echo "contribs_modules=$MODULES" >> "$GITHUB_OUTPUT"

      # Run package for each contrib without tests. This is needed, as some of the contribs have dependencies on each other.
      - name: Run package for each contrib without tests
        run: mvn package -pl ${{ steps.contribs.outputs.contribs_modules }} --also-make --batch-mode -Dmaven.test.skip=true -Dmatsim.preferLocalDtds=true

      # Run unit and integration tests for contrib modules with jacoco profile
      - name: Create coverage report for contrib modules
        run: mvn verify -P jacoco -pl ${{ steps.contribs.outputs.contribs_modules }} --batch-mode -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true

      - name: Push contribs code coverage to CodeCov
        uses: codecov/codecov-action@v5
        with:
          files: |
            contribs/*/target/site/jacoco/jacoco.xml
          flags: contribs
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

    env:
      MAVEN_OPTS: -Xmx2g
