name: deploy-on-pr-merge

on:
  push: # snapshot deployment
    branches:
      - moia-deployment
  pull_request_target: # pr-labelled deployment
    branches:
      - moia-deployment
    types:
      - closed

jobs:
  deploy-snapshot:
    name: deploy MOIA
    # for PR-labelled deployment -- only if closed by merging
    if: github.event_name == 'push' || github.event.pull_request.merged == true

    runs-on: ubuntu-latest

    environment: prd
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Deploy with Maven
        env:
          USERNAME: ${{github.actor}}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -pl org.matsim.contrib:drt,org.matsim.contrib:discrete_mode_choice deploy -am  --settings settings.xml -DskipTests=true -DaltSnapshotDeploymentRepository=github::default::https://maven.pkg.github.com/moia-oss/matsim-libs -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/moia-oss/matsim-libs