name: verify-merge-queue

on:
  merge_group:

jobs:
  build:
  runs-on: ubuntu-latest
  timeout-minutes: 45

  strategy:
    fail-fast: false
    matrix:
      module:
        - contribs/osm
        - contribs/application

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'zulu'
        cache: 'maven'

    - name: Build with Maven
      run: mvn install --batch-mode --also-make --projects ${{matrix.module}} -DskipTests -Dsource.skip

    - name: Test with Maven
      run: mvn verify --batch-mode -Dmaven.test.redirectTestOutputToFile -Dmatsim.preferLocalDtds=true --fail-at-end -Dsource.skip
      working-directory: ${{matrix.module}}

  env:
    MAVEN_OPTS: -Xmx2g

  verify-success:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Fail if unsuccessful
        if: needs.build.result != 'success'
        run: exit 1