//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 12:22:19 PM CET 
//


package playground.gregor.sim2d_v4.io.jaxb.sim2config01;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sim2DConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sim2DConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TimeStepSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="EventsInterval" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Sim2DEnvironments" type="{http://www.matsim.org/files/dtd}Sim2DEnvironmentsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sim2DConfigType", propOrder = {
    "timeStepSize",
    "eventsInterval",
    "sim2DEnvironments"
})
public class XMLSim2DConfigType {

    @XmlElement(name = "TimeStepSize", defaultValue = "0.1")
    protected Double timeStepSize;
    @XmlElement(name = "EventsInterval", defaultValue = "1")
    protected Integer eventsInterval;
    @XmlElement(name = "Sim2DEnvironments", required = true)
    protected XMLSim2DEnvironmentsType sim2DEnvironments;

    /**
     * Gets the value of the timeStepSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTimeStepSize() {
        return timeStepSize;
    }

    /**
     * Sets the value of the timeStepSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTimeStepSize(Double value) {
        this.timeStepSize = value;
    }

    /**
     * Gets the value of the eventsInterval property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getEventsInterval() {
        return eventsInterval;
    }

    /**
     * Sets the value of the eventsInterval property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setEventsInterval(Integer value) {
        this.eventsInterval = value;
    }

    /**
     * Gets the value of the sim2DEnvironments property.
     * 
     * @return
     *     possible object is
     *     {@link XMLSim2DEnvironmentsType }
     *     
     */
    public XMLSim2DEnvironmentsType getSim2DEnvironments() {
        return sim2DEnvironments;
    }

    /**
     * Sets the value of the sim2DEnvironments property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLSim2DEnvironmentsType }
     *     
     */
    public void setSim2DEnvironments(XMLSim2DEnvironmentsType value) {
        this.sim2DEnvironments = value;
    }

}
