//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.12.05 at 12:22:19 PM CET 
//


package playground.gregor.sim2d_v4.io.jaxb.sim2config01;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Sim2DEnvironmentsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Sim2DEnvironmentsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Sim2DEnvironment" type="{http://www.matsim.org/files/dtd}Sim2DEnvironmentType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Sim2DEnvironmentsType", propOrder = {
    "sim2DEnvironment"
})
public class XMLSim2DEnvironmentsType {

    @XmlElement(name = "Sim2DEnvironment", required = true)
    protected List<XMLSim2DEnvironmentType> sim2DEnvironment;

    /**
     * Gets the value of the sim2DEnvironment property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sim2DEnvironment property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSim2DEnvironment().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSim2DEnvironmentType }
     * 
     * 
     */
    public List<XMLSim2DEnvironmentType> getSim2DEnvironment() {
        if (sim2DEnvironment == null) {
            sim2DEnvironment = new ArrayList<XMLSim2DEnvironmentType>();
        }
        return this.sim2DEnvironment;
    }

}
